"""Typed operations of the MLIR ``bufferization`` dialect.

Generated by tools/gen_dialects.py. Do not edit.
"""

from .._mlir_python.bufferization import (
    AllocTensorOp as AllocTensorOp,
)
from .._mlir_python.bufferization import (
    CloneOp as CloneOp,
)
from .._mlir_python.bufferization import (
    DeallocOp as DeallocOp,
)
from .._mlir_python.bufferization import (
    DeallocTensorOp as DeallocTensorOp,
)
from .._mlir_python.bufferization import (
    MaterializeInDestinationOp as MaterializeInDestinationOp,
)
from .._mlir_python.bufferization import (
    ToBufferOp as ToBufferOp,
)
from .._mlir_python.bufferization import (
    ToTensorOp as ToTensorOp,
)

__all__ = [
    "AllocTensorOp",
    "CloneOp",
    "DeallocOp",
    "DeallocTensorOp",
    "MaterializeInDestinationOp",
    "ToBufferOp",
    "ToTensorOp",
]
