"""Typed operations of the MLIR ``cf`` dialect.

Generated by tools/gen_dialects.py. Do not edit.
"""

from .._mlir_python.cf import (
    AssertOp as AssertOp,
)
from .._mlir_python.cf import (
    BranchOp as BranchOp,
)
from .._mlir_python.cf import (
    CondBranchOp as CondBranchOp,
)
from .._mlir_python.cf import (
    SwitchOp as SwitchOp,
)

__all__ = [
    "AssertOp",
    "BranchOp",
    "CondBranchOp",
    "SwitchOp",
]
