"""Typed operations of the MLIR ``func`` dialect.

Generated by tools/gen_dialects.py. Do not edit.
"""

from .._mlir_python.func import (
    CallIndirectOp as CallIndirectOp,
)
from .._mlir_python.func import (
    CallOp as CallOp,
)
from .._mlir_python.func import (
    ConstantOp as ConstantOp,
)
from .._mlir_python.func import (
    FuncOp as FuncOp,
)
from .._mlir_python.func import (
    ReturnOp as ReturnOp,
)
from ._func_extras import (
    Returned as Returned,
)
from ._func_extras import (
    call as call,
)
from ._func_extras import (
    declare as declare,
)
from ._func_extras import (
    define as define,
)

__all__ = [
    "CallIndirectOp",
    "CallOp",
    "ConstantOp",
    "FuncOp",
    "ReturnOp",
    "Returned",
    "call",
    "declare",
    "define",
]
