"""Typed operations of the MLIR ``irdl`` dialect.

Generated by tools/gen_dialects.py. Do not edit.
"""

from .._mlir_python.irdl import (
    AllOfOp as AllOfOp,
)
from .._mlir_python.irdl import (
    AnyOfOp as AnyOfOp,
)
from .._mlir_python.irdl import (
    AnyOp as AnyOp,
)
from .._mlir_python.irdl import (
    AttributeOp as AttributeOp,
)
from .._mlir_python.irdl import (
    AttributesOp as AttributesOp,
)
from .._mlir_python.irdl import (
    BaseOp as BaseOp,
)
from .._mlir_python.irdl import (
    CPredOp as CPredOp,
)
from .._mlir_python.irdl import (
    DialectOp as DialectOp,
)
from .._mlir_python.irdl import (
    IsOp as IsOp,
)
from .._mlir_python.irdl import (
    OperandsOp as OperandsOp,
)
from .._mlir_python.irdl import (
    OperationOp as OperationOp,
)
from .._mlir_python.irdl import (
    ParametersOp as ParametersOp,
)
from .._mlir_python.irdl import (
    ParametricOp as ParametricOp,
)
from .._mlir_python.irdl import (
    RegionOp as RegionOp,
)
from .._mlir_python.irdl import (
    RegionsOp as RegionsOp,
)
from .._mlir_python.irdl import (
    ResultsOp as ResultsOp,
)
from .._mlir_python.irdl import (
    TypeOp as TypeOp,
)
from .._mlir_python.irdl import (
    Variadicity as Variadicity,
)
from .._mlir_python.irdl import (
    load_dialects as load_dialects,
)

__all__ = [
    "AllOfOp",
    "AnyOfOp",
    "AnyOp",
    "AttributeOp",
    "AttributesOp",
    "BaseOp",
    "CPredOp",
    "DialectOp",
    "IsOp",
    "OperandsOp",
    "OperationOp",
    "ParametersOp",
    "ParametricOp",
    "RegionOp",
    "RegionsOp",
    "ResultsOp",
    "TypeOp",
    "Variadicity",
    "load_dialects",
]
