"""Typed operations of the MLIR ``memref`` dialect.

Generated by tools/gen_dialects.py. Do not edit.
"""

from .._mlir_python.memref import (
    AllocaOp as AllocaOp,
)
from .._mlir_python.memref import (
    AllocaScopeOp as AllocaScopeOp,
)
from .._mlir_python.memref import (
    AllocaScopeReturnOp as AllocaScopeReturnOp,
)
from .._mlir_python.memref import (
    AllocOp as AllocOp,
)
from .._mlir_python.memref import (
    AssumeAlignmentOp as AssumeAlignmentOp,
)
from .._mlir_python.memref import (
    AtomicRMWOp as AtomicRMWOp,
)
from .._mlir_python.memref import (
    AtomicYieldOp as AtomicYieldOp,
)
from .._mlir_python.memref import (
    CastOp as CastOp,
)
from .._mlir_python.memref import (
    CollapseShapeOp as CollapseShapeOp,
)
from .._mlir_python.memref import (
    CopyOp as CopyOp,
)
from .._mlir_python.memref import (
    DeallocOp as DeallocOp,
)
from .._mlir_python.memref import (
    DimOp as DimOp,
)
from .._mlir_python.memref import (
    DistinctObjectsOp as DistinctObjectsOp,
)
from .._mlir_python.memref import (
    DmaStartOp as DmaStartOp,
)
from .._mlir_python.memref import (
    DmaWaitOp as DmaWaitOp,
)
from .._mlir_python.memref import (
    ExpandShapeOp as ExpandShapeOp,
)
from .._mlir_python.memref import (
    ExtractAlignedPointerAsIndexOp as ExtractAlignedPointerAsIndexOp,
)
from .._mlir_python.memref import (
    ExtractStridedMetadataOp as ExtractStridedMetadataOp,
)
from .._mlir_python.memref import (
    GenericAtomicRMWOp as GenericAtomicRMWOp,
)
from .._mlir_python.memref import (
    GetGlobalOp as GetGlobalOp,
)
from .._mlir_python.memref import (
    GlobalOp as GlobalOp,
)
from .._mlir_python.memref import (
    LoadOp as LoadOp,
)
from .._mlir_python.memref import (
    MemorySpaceCastOp as MemorySpaceCastOp,
)
from .._mlir_python.memref import (
    PrefetchOp as PrefetchOp,
)
from .._mlir_python.memref import (
    RankOp as RankOp,
)
from .._mlir_python.memref import (
    ReallocOp as ReallocOp,
)
from .._mlir_python.memref import (
    ReinterpretCastOp as ReinterpretCastOp,
)
from .._mlir_python.memref import (
    ReshapeOp as ReshapeOp,
)
from .._mlir_python.memref import (
    StoreOp as StoreOp,
)
from .._mlir_python.memref import (
    SubViewOp as SubViewOp,
)
from .._mlir_python.memref import (
    TransposeOp as TransposeOp,
)
from .._mlir_python.memref import (
    ViewOp as ViewOp,
)

__all__ = [
    "AllocOp",
    "AllocaOp",
    "AllocaScopeOp",
    "AllocaScopeReturnOp",
    "AssumeAlignmentOp",
    "AtomicRMWOp",
    "AtomicYieldOp",
    "CastOp",
    "CollapseShapeOp",
    "CopyOp",
    "DeallocOp",
    "DimOp",
    "DistinctObjectsOp",
    "DmaStartOp",
    "DmaWaitOp",
    "ExpandShapeOp",
    "ExtractAlignedPointerAsIndexOp",
    "ExtractStridedMetadataOp",
    "GenericAtomicRMWOp",
    "GetGlobalOp",
    "GlobalOp",
    "LoadOp",
    "MemorySpaceCastOp",
    "PrefetchOp",
    "RankOp",
    "ReallocOp",
    "ReinterpretCastOp",
    "ReshapeOp",
    "StoreOp",
    "SubViewOp",
    "TransposeOp",
    "ViewOp",
]
