"""Typed operations of the MLIR ``scf`` dialect.

Generated by tools/gen_dialects.py. Do not edit.
"""

from .._mlir_python.scf import (
    ConditionOp as ConditionOp,
)
from .._mlir_python.scf import (
    ExecuteRegionOp as ExecuteRegionOp,
)
from .._mlir_python.scf import (
    ForallOp as ForallOp,
)
from .._mlir_python.scf import (
    ForOp as ForOp,
)
from .._mlir_python.scf import (
    IfOp as IfOp,
)
from .._mlir_python.scf import (
    IndexSwitchOp as IndexSwitchOp,
)
from .._mlir_python.scf import (
    InParallelOp as InParallelOp,
)
from .._mlir_python.scf import (
    ParallelOp as ParallelOp,
)
from .._mlir_python.scf import (
    ReduceOp as ReduceOp,
)
from .._mlir_python.scf import (
    ReduceReturnOp as ReduceReturnOp,
)
from .._mlir_python.scf import (
    WhileOp as WhileOp,
)
from .._mlir_python.scf import (
    YieldOp as YieldOp,
)

__all__ = [
    "ConditionOp",
    "ExecuteRegionOp",
    "ForOp",
    "ForallOp",
    "IfOp",
    "InParallelOp",
    "IndexSwitchOp",
    "ParallelOp",
    "ReduceOp",
    "ReduceReturnOp",
    "WhileOp",
    "YieldOp",
]
