"""Typed MLIR passes, one class per pass linked into this build.

Build pipelines with ``PassManager`` and ``Nested``::

    pm = PassManager(Module, [Canonicalizer(), Nested(func.FuncOp, [CSE()])])
    pm.run(module)

Each class's fields are the pass's options, with MLIR's defaults.

Generated by tools/gen_passes.py. Do not edit.
"""

from __future__ import annotations

import dataclasses
import enum
from collections.abc import Sequence
from typing import ClassVar

from ._mlir_python import Module, Operation
from ._passes import Nested, Pass, PassManager, PipelineElement


class GreedySimplifyRegionLevel(enum.Enum):
    """Values of the option: Perform control flow optimizations to the region tree."""

    DISABLED = "disabled"
    """Don't run any control-flow simplification."""

    NORMAL = "normal"
    """Perform simple control-flow simplifications (e.g. dead args elimination)."""

    AGGRESSIVE = "aggressive"
    """Perform aggressive control-flow simplification (e.g. block merging)."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ArithToLLVMConversion(Pass):
    """``convert-arith-to-llvm``: Convert Arith dialect to LLVM dialect

    This pass converts supported Arith ops to LLVM dialect instructions.
    """

    ARGUMENT: ClassVar[str] = "convert-arith-to-llvm"

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class BubbleDownMemorySpaceCasts(Pass):
    """``bubble-down-memory-space-casts``: Bubbles down memory-space cast operations.

    This pass tries to iteratively bubble down all possible memory-space cast
    operations. It is important to note that the determination of which casts
    are bubbled down is based on the interfaces
    `MemorySpaceCastConsumerOpInterface`, and `MemorySpaceCastOpInterface`, and
    not the pass. The pass only looks for operations implementing the
    `MemorySpaceCastConsumerOpInterface` interface, and invoking the interface
    methods to perform the bubbling down.

    Example:

    ```mlir
    func.func @op_with_cast_sequence(%arg0: memref<4x4xf32, 1>, %arg1: index, %arg2: f32) -> memref<16xf32> {
      %memspacecast = memref.memory_space_cast %arg0 : memref<4x4xf32, 1> to memref<4x4xf32>
      %c0 = arith.constant 0 : index
      %c4 = arith.constant 4 : index
      %expanded = memref.expand_shape %memspacecast [[0], [1, 2]] output_shape [4, 2, 2] : memref<4x4xf32> into memref<4x2x2xf32>
      %collapsed = memref.collapse_shape %expanded [[0, 1, 2]] : memref<4x2x2xf32> into memref<16xf32>
      %loaded = memref.load %collapsed[%c0] : memref<16xf32>
      %added = arith.addf %loaded, %arg2 : f32
      memref.store %added, %collapsed[%c0] : memref<16xf32>
      %atomic_result = memref.atomic_rmw addf %arg2, %collapsed[%c4] : (f32, memref<16xf32>) -> f32
      return %collapsed : memref<16xf32>
    }
    // mlir-opt --bubble-down-memory-space-casts
    func.func @op_with_cast_sequence(%arg0: memref<4x4xf32, 1>, %arg1: index, %arg2: f32) -> memref<16xf32> {
      %c4 = arith.constant 4 : index
      %c0 = arith.constant 0 : index
      %expand_shape = memref.expand_shape %arg0 [[0], [1, 2]] output_shape [4, 2, 2] : memref<4x4xf32, 1> into memref<4x2x2xf32, 1>
      %collapse_shape = memref.collapse_shape %expand_shape [[0, 1, 2]] : memref<4x2x2xf32, 1> into memref<16xf32, 1>
      %memspacecast = memref.memory_space_cast %collapse_shape : memref<16xf32, 1> to memref<16xf32>
      %0 = memref.load %collapse_shape[%c0] : memref<16xf32, 1>
      %1 = arith.addf %0, %arg2 : f32
      memref.store %1, %collapse_shape[%c0] : memref<16xf32, 1>
      %2 = memref.atomic_rmw addf %arg2, %collapse_shape[%c4] : (f32, memref<16xf32, 1>) -> f32
      return %memspacecast : memref<16xf32>
    }
    ```
    """

    ARGUMENT: ClassVar[str] = "bubble-down-memory-space-casts"


@dataclasses.dataclass(frozen=True, kw_only=True)
class CSE(Pass):
    """``cse``: Eliminate common sub-expressions

    This pass implements a generalized algorithm for common sub-expression
    elimination. This pass relies on information provided by the
    `Memory SideEffect` interface to identify when it is safe to eliminate
    operations. See [Common subexpression elimination](https://en.wikipedia.org/wiki/Common_subexpression_elimination)
    for more general details on this optimization.
    """

    ARGUMENT: ClassVar[str] = "cse"


@dataclasses.dataclass(frozen=True, kw_only=True)
class Canonicalizer(Pass):
    """``canonicalize``: Canonicalize operations

    This pass performs various types of canonicalizations over a set of
    operations by iteratively applying the canonicalization patterns of all
    loaded dialects until either a fixpoint is reached or the maximum number of
    iterations/rewrites is exhausted. Canonicalization is best-effort and does
    not guarantee that the entire IR is in a canonical form after running this
    pass. See [Operation Canonicalization](Canonicalization.md) for more
    details.
    """

    ARGUMENT: ClassVar[str] = "canonicalize"

    top_down: bool = dataclasses.field(default=True, metadata={"argument": "top-down"})
    """Seed the worklist in general top-down order"""

    region_simplify: GreedySimplifyRegionLevel = dataclasses.field(
        default=GreedySimplifyRegionLevel.NORMAL,
        metadata={"argument": "region-simplify"},
    )
    """Perform control flow optimizations to the region tree"""

    max_iterations: int = dataclasses.field(
        default=10, metadata={"argument": "max-iterations"}
    )
    """Max. iterations between applying patterns / simplifying regions"""

    max_num_rewrites: int = dataclasses.field(
        default=-1, metadata={"argument": "max-num-rewrites"}
    )
    """Max. number of pattern rewrites within an iteration"""

    test_convergence: bool = dataclasses.field(
        default=False, metadata={"argument": "test-convergence"}
    )
    """Test only: Fail pass on non-convergence to detect cyclic pattern"""

    disable_patterns: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "disable-patterns"}
    )
    """Labels of patterns that should be filtered out during application"""

    enable_patterns: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "enable-patterns"}
    )
    """Labels of patterns that should be used during application, all other patterns are filtered out"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class CompositeFixedPoint(Pass):
    """``composite-fixed-point-pass``: Composite fixed point pass

    Composite pass runs provided set of passes until fixed point or maximum
    number of iterations reached.
    """

    ARGUMENT: ClassVar[str] = "composite-fixed-point-pass"

    name: str = dataclasses.field(
        default="CompositeFixedPointPass", metadata={"argument": "name"}
    )
    """Composite pass display name"""

    pipeline: str = dataclasses.field(default="", metadata={"argument": "pipeline"})
    """Composite pass inner pipeline"""

    max_iterations: int = dataclasses.field(
        default=10, metadata={"argument": "max-iterations"}
    )
    """Maximum number of iterations if inner pipeline"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ControlFlowSink(Pass):
    """``control-flow-sink``: Sink operations into conditional blocks

    This pass implements control-flow sink on operations that implement
    `RegionBranchOpInterface` by moving dominating operations whose only uses
    are in a conditionally-executed regions into those regions so that
    executions paths where their results are not needed do not perform
    unnecessary computations.

    This is similar (but opposite) to loop-invariant code motion, which hoists
    operations out of regions executed more than once. The implementation of
    control-flow sink uses a simple and conversative cost model: operations are
    never duplicated and are only moved into singly-executed regions.

    It is recommended to run canonicalization first to remove unreachable
    blocks: ops in unreachable blocks may prevent other operations from being
    sunk as they may contain uses of their results
    """

    ARGUMENT: ClassVar[str] = "control-flow-sink"


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertControlFlowToLLVM(Pass):
    """``convert-cf-to-llvm``: Convert ControlFlow operations to the LLVM dialect

    Convert ControlFlow operations into LLVM IR dialect operations.

    If other operations are present and their results are required by the LLVM
    IR dialect operations, the pass will fail.  Any LLVM IR operations or types
    already present in the IR will be kept as is.
    """

    ARGUMENT: ClassVar[str] = "convert-cf-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertFuncToLLVM(Pass):
    """``convert-func-to-llvm``: Convert from the Func dialect to the LLVM dialect

    Convert Func dialect operations into the LLVM IR dialect operations.

    #### Input invariant

    -   no `tensor` types;
    -   all `vector` are one-dimensional;
    -   all blocks are reachable by following the successors of the first basic
        block;

    If other operations are present and their results are required by the LLVM
    IR dialect operations, the pass will fail.  Any LLVM IR operations or types
    already present in the IR will be kept as is.

    An LLVM datalayout string can be attached as an attribute to the module on
    which the pass anchors. Such an attribute is attached by calling the
    set-module-datalayout pass. If present, an llvm::DataLayout object is
    created from this attribute and used in the conversion to LLVM.

    #### Output IR

    Functions converted to LLVM IR. Function arguments types are converted
    one-to-one. Function results are converted one-to-one and, in case more than
    1 value is returned, packed into an LLVM IR struct type. Function calls and
    returns are updated accordingly. Block argument types are updated to use
    LLVM IR types.
    """

    ARGUMENT: ClassVar[str] = "convert-func-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    use_bare_ptr_memref_call_conv: bool = dataclasses.field(
        default=False, metadata={"argument": "use-bare-ptr-memref-call-conv"}
    )
    """Replace FuncOp's MemRef arguments with bare pointers to the MemRef element types"""

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertMathToLLVM(Pass):
    """``convert-math-to-llvm``: Convert Math dialect to LLVM dialect"""

    ARGUMENT: ClassVar[str] = "convert-math-to-llvm"

    approximate_log1p: bool = dataclasses.field(
        default=True, metadata={"argument": "approximate-log1p"}
    )
    """Enable approximation of Log1p."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertToLLVM(Pass):
    """``convert-to-llvm``: Convert to LLVM via dialect interfaces found in the input IR

    This is a generic pass to convert to LLVM, it uses the
    `ConvertToLLVMPatternInterface` dialect interface to delegate to dialects
    the injection of conversion patterns.

    If `dynamic` is set to `true`, the pass will look for
    `ConvertToLLVMAttrInterface` attributes and use them to further configure
    the conversion process. This option also uses the `DataLayoutAnalysis`
    analysis to configure the type converter. Enabling this option incurs in
    extra overhead.
    """

    ARGUMENT: ClassVar[str] = "convert-to-llvm"

    filter_dialects: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "filter-dialects"}
    )
    """Test conversion patterns of only the specified dialects"""

    dynamic: bool = dataclasses.field(default=False, metadata={"argument": "dynamic"})
    """Use op conversion attributes to configure the conversion"""

    allow_pattern_rollback: bool = dataclasses.field(
        default=True, metadata={"argument": "allow-pattern-rollback"}
    )
    """Experimental performance flag to disallow pattern rollback"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class FinalizeMemRefToLLVMConversion(Pass):
    """``finalize-memref-to-llvm``: Finalize MemRef dialect to LLVM dialect conversion

    Finalize the conversion of the operations from the MemRef
    dialect to the LLVM dialect.
    This conversion will not convert some complex MemRef
    operations. Make sure to run `expand-strided-metadata`
    beforehand for these.
    """

    ARGUMENT: ClassVar[str] = "finalize-memref-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    use_aligned_alloc: bool = dataclasses.field(
        default=False, metadata={"argument": "use-aligned-alloc"}
    )
    """Use aligned_alloc in place of malloc for heap allocations"""

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""

    use_generic_functions: bool = dataclasses.field(
        default=False, metadata={"argument": "use-generic-functions"}
    )
    """Use generic allocation and deallocation functions instead of the classic 'malloc', 'aligned_alloc' and 'free' functions"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class GenerateRuntimeVerification(Pass):
    """``generate-runtime-verification``: Generate additional runtime op verification checks

    This pass generates op-specific runtime checks using the
    `RuntimeVerifiableOpInterface`. It can be run for debugging purposes after
    passes that are suspected to introduce faulty IR.
    """

    ARGUMENT: ClassVar[str] = "generate-runtime-verification"

    verbose_level: int = dataclasses.field(
        default=1, metadata={"argument": "verbose-level"}
    )
    """Verbosity level for runtime verification messages: 0 = Minimum (only source location), 1 = Detailed (include full operation details, names, types, shapes, etc.)"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class Inliner(Pass):
    """``inline``: Inline function calls"""

    ARGUMENT: ClassVar[str] = "inline"

    default_pipeline: str = dataclasses.field(
        default="canonicalize", metadata={"argument": "default-pipeline"}
    )
    """The optimizer pipeline used for callables that do not have a dedicated optimizer pipeline in opPipelineList"""

    op_pipelines: Sequence[Nested] = dataclasses.field(
        default=(), metadata={"argument": "op-pipelines"}
    )
    """Callable operation specific optimizer pipelines (in the form of `dialect.op(pipeline)`)"""

    max_iterations: int = dataclasses.field(
        default=4, metadata={"argument": "max-iterations"}
    )
    """Maximum number of iterations when inlining within an SCC"""

    inlining_threshold: int = dataclasses.field(
        default=-1, metadata={"argument": "inlining-threshold"}
    )
    """If the ratio between the number of the operations in the callee and the number of the operations in the caller exceeds this value (in percentage), then the callee is not inlined even if it is legal to inline it"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class LocationSnapshot(Pass):
    """``snapshot-op-locations``: Generate new locations from the current IR

    This pass allows for generating new locations from the IR during any stage
    of compilation, by snapshotting the IR to a file and using that file to
    generate new locations for the operations.

    Depending on the value of the `tag` option, different resulting locations
    may be generated:

    * If unset, the original location of the operation is replaced.

    Example:

    ```mlir
    // old:
    ... loc("original_source.cpp":1:1)

    // new:
    ... loc("snapshot_source.mlir":10:10)
    ```

    * If set, the new location is fused with the original location in the form
    of a [`Name Location`](Dialects/Builtin.md/#nameloc) with the specified tag.

    Example:

    ```mlir
    // old:
    ... loc("original_source.cpp":1:1)

    // new:
    ... loc(fused["original_source.cpp":1:1, "snapshot"("snapshot_source.mlir":10:10)])
    ```
    """

    ARGUMENT: ClassVar[str] = "snapshot-op-locations"

    filename: str = dataclasses.field(default="", metadata={"argument": "filename"})
    """The filename to print the generated IR"""

    tag: str = dataclasses.field(default="", metadata={"argument": "tag"})
    """A tag to use when fusing the new locations with the original. If unset, the locations are replaced."""

    print_debuginfo: bool = dataclasses.field(
        default=False, metadata={"argument": "print-debuginfo"}
    )
    """Print debug info in MLIR output"""

    print_op_generic: bool = dataclasses.field(
        default=False, metadata={"argument": "print-op-generic"}
    )
    """Print the generic op form"""

    print_local_scope: bool = dataclasses.field(
        default=False, metadata={"argument": "print-local-scope"}
    )
    """Print with local scope and inline information (eliding aliases for attributes, types, and locations"""

    pretty_debuginfo: bool = dataclasses.field(
        default=False, metadata={"argument": "pretty-debuginfo"}
    )
    """Print pretty debug info in MLIR output"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class LoopInvariantCodeMotion(Pass):
    """``loop-invariant-code-motion``: Hoist loop invariant instructions outside of the loop"""

    ARGUMENT: ClassVar[str] = "loop-invariant-code-motion"


@dataclasses.dataclass(frozen=True, kw_only=True)
class LoopInvariantSubsetHoisting(Pass):
    """``loop-invariant-subset-hoisting``: Hoist loop invariant subset ops outside of the loop"""

    ARGUMENT: ClassVar[str] = "loop-invariant-subset-hoisting"


@dataclasses.dataclass(frozen=True, kw_only=True)
class Mem2Reg(Pass):
    """``mem2reg``: Promotes memory slots into values.

    This pass removes loads out of and stores into a memory slot, and turns
    them into direct uses of SSA values. This is done generically using the
    `PromotableAllocationOpInterface`, `PromotableOpInterface` and
    `PromotableMemOpInterface` interfaces.

    This pass will attempt to compute which definitions of the content of
    the memory slot reach operations that use the memory slot pointer. It
    will rewire or remove operations that use the slot pointer so they no
    longer use it. If any of this is not possible, the IR will be left
    without mutation.

    This pass only supports unstructured control-flow. Promotion of operations
    within subregions will not happen.
    """

    ARGUMENT: ClassVar[str] = "mem2reg"

    region_simplify: bool = dataclasses.field(
        default=True, metadata={"argument": "region-simplify"}
    )
    """Perform control flow optimizations to the region tree"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class PrintIR(Pass):
    """``print-ir``: Print IR on the debug stream

    Print the entire IR on the debug stream. This is meant for debugging
    purposes to inspect the IR at a specific point in the pipeline.
    """

    ARGUMENT: ClassVar[str] = "print-ir"

    label: str = dataclasses.field(default="", metadata={"argument": "label"})
    """Label"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class PrintOpStats(Pass):
    """``print-op-stats``: Print statistics of operations"""

    ARGUMENT: ClassVar[str] = "print-op-stats"

    json: bool = dataclasses.field(default=False, metadata={"argument": "json"})
    """print the stats as JSON"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ReconcileUnrealizedCasts(Pass):
    """``reconcile-unrealized-casts``: Simplify and eliminate unrealized conversion casts

    Eliminate `unrealized_conversion_cast` operations, commonly introduced by
    partial dialect conversions, that transitively convert a value to another
    value of the same type, that is:

    ```
    %0 = "producer.op"() : () -> !type.A
    %1 = unrealized_conversion_cast %0 : !type.A to !type.B
    %2 = unrealized_conversion_cast %1 : !type.B to !type.C
    %3 = unrealized_conversion_cast %2 : !type.C to !type.A
    "consumer.op"(%3) : (!type.A) -> ()
    ```

    Such situations appear when the consumer operation is converted by one pass
    and the producer operation is converted by another pass, each of which
    produces an unrealized cast. This pass can be used to clean up the IR.
    """

    ARGUMENT: ClassVar[str] = "reconcile-unrealized-casts"


@dataclasses.dataclass(frozen=True, kw_only=True)
class RemoveDeadValues(Pass):
    """``remove-dead-values``: Remove dead values

    The goal of this pass is optimization (reducing runtime) by removing
    unnecessary instructions. Unlike other passes that rely on local information
    gathered from patterns to accomplish optimization, this pass uses a full
    analysis of the IR, specifically, liveness analysis, and is thus more
    powerful.

    Currently, this pass performs the following optimizations:
    (A) Removes function arguments that are not live,
    (B) Removes function return values that are not live across all callers of
    the function,
    (C) Removes unneccesary operands, results, region arguments, and region
    terminator operands of region branch ops, and,
    (D) Removes simple and region branch ops that have all non-live results and
    don't affect memory in any way,

    iff

    the IR doesn't have any non-function symbol ops, non-call symbol user ops
    and branch ops.

    Here, a "simple op" refers to an op that isn't a symbol op, symbol-user op,
    region branch op, branch op, region branch terminator op, or return-like.

    It is noteworthy that we do not refer to non-live values as "dead" in this
    file to avoid confusing it with dead code analysis's "dead", which refers to
    unreachable code (code that never executes on hardware) while "non-live"
    refers to code that executes on hardware but is unnecessary. Thus, while the
    removal of dead code helps little in reducing runtime, removing non-live
    values should theoretically have significant impact (depending on the amount
    removed).

    It is also important to note that unlike other passes (like `canonicalize`)
    that apply op-specific optimizations through patterns, this pass uses
    different interfaces to handle various types of ops and tries to cover all
    existing ops through these interfaces.

    It is because of its reliance on (a) liveness analysis and (b) interfaces
    that makes it so powerful that it can optimize ops that don't have a
    canonicalizer and even when an op does have a canonicalizer, it can perform
    more aggressive optimizations, as observed in the test files associated with
    this pass.

    Example of optimization (A):-

    ```
    int add_2_to_y(int x, int y) {
      return 2 + y
    }

    print(add_2_to_y(3, 4))
    print(add_2_to_y(5, 6))
    ```

    becomes

    ```
    int add_2_to_y(int y) {
      return 2 + y
    }

    print(add_2_to_y(4))
    print(add_2_to_y(6))
    ```

    Example of optimization (B):-

    ```
    int, int get_incremented_values(int y) {
      store y somewhere in memory
      return y + 1, y + 2
    }

    y1, y2 = get_incremented_values(4)
    y3, y4 = get_incremented_values(6)
    print(y2)
    ```

    becomes

    ```
    int get_incremented_values(int y) {
      store y somewhere in memory
      return y + 2
    }

    y2 = get_incremented_values(4)
    y4 = get_incremented_values(6)
    print(y2)
    ```

    Example of optimization (C):-

    Assume only `%result1` is live here. Then,

    ```
    %result1, %result2, %result3 = scf.while (%arg1 = %operand1, %arg2 = %operand2) {
      %terminator_operand2 = add %arg2, %arg2
      %terminator_operand3 = mul %arg2, %arg2
      %terminator_operand4 = add %arg1, %arg1
      scf.condition(%terminator_operand1) %terminator_operand2, %terminator_operand3, %terminator_operand4
    } do {
    ^bb0(%arg3, %arg4, %arg5):
      %terminator_operand6 = add %arg4, %arg4
      %terminator_operand5 = add %arg5, %arg5
      scf.yield %terminator_operand5, %terminator_operand6
    }
    ```

    becomes

    ```
    %result1, %result2 = scf.while (%arg2 = %operand2) {
      %terminator_operand2 = add %arg2, %arg2
      %terminator_operand3 = mul %arg2, %arg2
      scf.condition(%terminator_operand1) %terminator_operand2, %terminator_operand3
    } do {
    ^bb0(%arg3, %arg4):
      %terminator_operand6 = add %arg4, %arg4
      scf.yield %terminator_operand6
    }
    ```

    It is interesting to see that `%result2` won't be removed even though it is
    not live because `%terminator_operand3` forwards to it and cannot be
    removed. And, that is because it also forwards to `%arg4`, which is live.

    Example of optimization (D):-

    ```
    int square_and_double_of_y(int y) {
      square = y ^ 2
      double = y * 2
      return square, double
    }

    sq, do = square_and_double_of_y(5)
    print(do)
    ```

    becomes

    ```
    int square_and_double_of_y(int y) {
      double = y * 2
      return double
    }

    do = square_and_double_of_y(5)
    print(do)
    ```

    Note: If `canonicalize` is set to "false", this pass does not remove any
    block arguments / op results from ops that implement the
    RegionBranchOpInterface. Instead, it just sets dead operands to
    "ub.poison".
    """

    ARGUMENT: ClassVar[str] = "remove-dead-values"

    canonicalize: bool = dataclasses.field(
        default=True, metadata={"argument": "canonicalize"}
    )
    """Canonicalize region branch ops"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class SCCP(Pass):
    """``sccp``: Sparse Conditional Constant Propagation

    This pass implements a general algorithm for sparse conditional constant
    propagation. This algorithm detects values that are known to be constant and
    optimistically propagates this throughout the IR. Any values proven to be
    constant are replaced, and removed if possible.

    This implementation is based on the algorithm described by Wegman and Zadeck
    in [“Constant Propagation with Conditional Branches”](https://dl.acm.org/doi/10.1145/103135.103136) (1991).
    """

    ARGUMENT: ClassVar[str] = "sccp"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SCFToControlFlow(Pass):
    """``convert-scf-to-cf``: Convert SCF dialect to ControlFlow dialect, replacing structured control flow with a CFG"""

    ARGUMENT: ClassVar[str] = "convert-scf-to-cf"

    allow_pattern_rollback: bool = dataclasses.field(
        default=True, metadata={"argument": "allow-pattern-rollback"}
    )
    """Experimental performance flag to disallow pattern rollback"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class SROA(Pass):
    """``sroa``: Scalar Replacement of Aggregates

    Scalar Replacement of Aggregates. Replaces allocations of aggregates into
    independant allocations of its elements.

    Allocators must implement `DestructurableAllocationOpInterface` to provide
    the list of memory slots for which destructuring should be attempted.

    This pass will only be applied if all accessors of the aggregate implement
    the `DestructurableAccessorOpInterface`. If the accessors provide a view
    into the struct, users of the view must ensure it is used in a type-safe
    manner and within bounds by implementing `TypeSafeOpInterface`.
    """

    ARGUMENT: ClassVar[str] = "sroa"


@dataclasses.dataclass(frozen=True, kw_only=True)
class StripDebugInfo(Pass):
    """``strip-debuginfo``: Strip debug info from all operations

    This pass strips the IR of any location information, by replacing all
    operation locations with [`unknown`](Dialects/Builtin.md/#unknownloc).
    """

    ARGUMENT: ClassVar[str] = "strip-debuginfo"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SymbolDCE(Pass):
    """``symbol-dce``: Eliminate dead symbols

    This pass deletes all symbols that are found to be unreachable. This is done
    by computing the set of operations that are known to be live, propagating
    that liveness to other symbols, and then deleting all symbols that are not
    within this live set. Live symbols are those that have a
    [visibility](SymbolsAndSymbolTables.md/#symbol-visibility) that extends
    beyond the IR, e.g. `public`, or those that are referenced by live symbols
    or other non-Symbol operations.

    For example, consider the following input:

    ```mlir
    func.func private @dead_private_function()
    func.func private @live_private_function()

    // Note: The `public` isn't necessary here, as this is the default.
    func.func public @public_function() {
      "foo.return"() {uses = [@live_private_function]} : () -> ()
    }
    ```

    A known live function, `public_function`, contains a reference to an
    otherwise non-live function `live_private_function`. After running
    `symbol-dce`, only these two symbols should remain, as the final symbol
    `dead_private_function` is not visible outside of the current IR and there
    are no links to known-live operations. After running, we get the expected:

    ```mlir
    func.func private @live_private_function()

    func.func public @public_function() {
      "foo.return"() {uses = [@live_private_function]} : () -> ()
    }
    ```

    See [Symbols and SymbolTables](SymbolsAndSymbolTables.md) for more
    information on `Symbols`.
    """

    ARGUMENT: ClassVar[str] = "symbol-dce"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SymbolPrivatize(Pass):
    """``symbol-privatize``: Mark symbols private

    This pass marks all top-level symbols of the operation run as `private`
    except if listed in `exclude` pass option.
    """

    ARGUMENT: ClassVar[str] = "symbol-privatize"

    exclude: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "exclude"}
    )
    """Comma separated list of symbols that should not be marked private"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class TopologicalSort(Pass):
    """``topological-sort``: Sort regions without SSA dominance in topological order

    Recursively sorts all nested regions without SSA dominance in topological
    order. The main purpose is readability, as well as potentially processing of
    certain transformations and analyses. The function sorts the operations in
    all nested regions such that, as much as possible, all users appear after
    their producers.

    This sort is stable. If the block is already topologically sorted, the IR
    is not changed. Operations that form a cycle are moved to the end of the
    regions in a stable order.
    """

    ARGUMENT: ClassVar[str] = "topological-sort"


@dataclasses.dataclass(frozen=True, kw_only=True)
class UBToLLVMConversion(Pass):
    """``convert-ub-to-llvm``: Convert UB dialect to LLVM dialect

    This pass converts supported UB ops to LLVM dialect instructions.
    """

    ARGUMENT: ClassVar[str] = "convert-ub-to-llvm"

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ViewOpGraph(Pass):
    """``view-op-graph``: Print Graphviz visualization of an operation

    This pass prints a Graphviz graph of a module.

    - Operations are represented as nodes;
    - Uses (data flow) as edges;
    - Control flow as dashed edges;
    - Regions/blocks as subgraphs.

    By default, only data flow edges are printed.

    Note: See https://www.graphviz.org/doc/info/lang.html for more information
    about the Graphviz DOT language.
    """

    ARGUMENT: ClassVar[str] = "view-op-graph"

    max_label_len: int = dataclasses.field(
        default=20, metadata={"argument": "max-label-len"}
    )
    """Limit attribute/type length to number of chars"""

    print_attrs: bool = dataclasses.field(
        default=True, metadata={"argument": "print-attrs"}
    )
    """Print attributes of operations"""

    print_control_flow_edges: bool = dataclasses.field(
        default=False, metadata={"argument": "print-control-flow-edges"}
    )
    """Print control flow edges"""

    print_data_flow_edges: bool = dataclasses.field(
        default=True, metadata={"argument": "print-data-flow-edges"}
    )
    """Print data flow edges"""

    print_result_types: bool = dataclasses.field(
        default=True, metadata={"argument": "print-result-types"}
    )
    """Print result types of operations"""


__all__ = [
    "CSE",
    "SCCP",
    "SROA",
    "ArithToLLVMConversion",
    "BubbleDownMemorySpaceCasts",
    "Canonicalizer",
    "CompositeFixedPoint",
    "ControlFlowSink",
    "ConvertControlFlowToLLVM",
    "ConvertFuncToLLVM",
    "ConvertMathToLLVM",
    "ConvertToLLVM",
    "FinalizeMemRefToLLVMConversion",
    "GenerateRuntimeVerification",
    "GreedySimplifyRegionLevel",
    "Inliner",
    "LocationSnapshot",
    "LoopInvariantCodeMotion",
    "LoopInvariantSubsetHoisting",
    "Mem2Reg",
    "Nested",
    "Pass",
    "PassManager",
    "PipelineElement",
    "PrintIR",
    "PrintOpStats",
    "ReconcileUnrealizedCasts",
    "RemoveDeadValues",
    "SCFToControlFlow",
    "StripDebugInfo",
    "SymbolDCE",
    "SymbolPrivatize",
    "TopologicalSort",
    "UBToLLVMConversion",
    "ViewOpGraph",
]
