"""Typed MLIR passes, one class per pass linked into this build.

Build pipelines with ``PassManager`` and ``Nested``::

    pm = PassManager(Module, [Canonicalizer(), Nested(func.FuncOp, [CSE()])])
    pm.run(module)

Each class's fields are the pass's options, with MLIR's defaults.

Generated by tools/gen_passes.py. Do not edit.
"""

from __future__ import annotations

import dataclasses
import enum
from collections.abc import Sequence
from typing import ClassVar

from ._mlir_python import Module, Operation
from ._passes import Nested, Pass, PassManager, PipelineElement, PythonPass
from .dialects import func


class GreedySimplifyRegionLevel(enum.Enum):
    """Values of the option: Perform control flow optimizations to the region tree."""

    DISABLED = "disabled"
    """Don't run any control-flow simplification."""

    NORMAL = "normal"
    """Perform simple control-flow simplifications (e.g. dead args elimination)."""

    AGGRESSIVE = "aggressive"
    """Perform aggressive control-flow simplification (e.g. block merging)."""


class LanguageTarget(enum.Enum):
    """Values of the option: Select the language standard target for callees (c99 or cpp11)."""

    C99 = "c99"
    """c99"""

    CPP11 = "cpp11"
    """cpp11"""


class LayoutMapOption(enum.Enum):
    """Values of the option: Controls layout maps when bufferizing function signatures."""

    INFER_LAYOUT_MAP = "infer-layout-map"

    IDENTITY_LAYOUT_MAP = "identity-layout-map"

    FULLY_DYNAMIC_LAYOUT_MAP = "fully-dynamic-layout-map"


class VectorContractLowering(enum.Enum):
    """Values of the option: control the lowering of `vector.contract` operations."""

    DOT = "dot"
    """Progressively lower to finer grained `vector.contract` and dot-products. (default)"""

    LLVMINTR = "llvmintr"
    """Lower directly to `llvm.intr.matrix.multiply`."""

    OUTERPRODUCT = "outerproduct"
    """Lower to `vector.outerproduct`."""

    PARALLELARITH = "parallelarith"
    """Lower contract with all reduction dimensions unrolled to 1 to a vector elementwise operations."""


class VectorMultiReductionLowering(enum.Enum):
    """Values of the option: Select the strategy to control how multi_reduction is lowered."""

    INNER_PARALLEL = "inner-parallel"
    """Lower multi_reduction into outer-reduction and inner-parallel ops."""

    INNER_REDUCTION = "inner-reduction"
    """Lower multi_reduction into outer-parallel and inner-reduction ops."""


class VectorTransposeLowering(enum.Enum):
    """Values of the option: control the lowering of `vector.transpose` operations."""

    ELTWISE = "eltwise"
    """Lower transpose into element-wise extract and inserts (default)"""

    LLVMINTR = "llvmintr"
    """Lower 2-D transpose directly to `llvm.intr.matrix.transpose`"""

    SHUFFLE1D = "shuffle1d"
    """Lower 2-D transpose to `vector.shuffle` on 1-D vector."""

    SHUFFLE16X16 = "shuffle16x16"
    """Lower 2-D transpose to `vector.shuffle` on 16x16 vector."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ArithToLLVMConversion(Pass):
    """``convert-arith-to-llvm``: Convert Arith dialect to LLVM dialect

    This pass converts supported Arith ops to LLVM dialect instructions.
    """

    ARGUMENT: ClassVar[str] = "convert-arith-to-llvm"

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class AsyncFuncToAsyncRuntime(Pass):
    """``async-func-to-async-runtime``: Lower async.func operations to the explicit async.runtime andasync.coro operations"""

    ARGUMENT: ClassVar[str] = "async-func-to-async-runtime"
    ANCHOR: ClassVar[type[Operation] | None] = Module


@dataclasses.dataclass(frozen=True, kw_only=True)
class AsyncParallelFor(Pass):
    """``async-parallel-for``: Convert scf.parallel operations to multiple async compute ops executed concurrently for non-overlapping iteration ranges"""

    ARGUMENT: ClassVar[str] = "async-parallel-for"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    async_dispatch: bool = dataclasses.field(
        default=True, metadata={"argument": "async-dispatch"}
    )
    """Dispatch async compute tasks using recursive work splitting. If `false` async compute tasks will be launched using simple for loop in the caller thread."""

    num_workers: int = dataclasses.field(
        default=8, metadata={"argument": "num-workers"}
    )
    """The number of available workers to execute async operations. If `-1` the value will be retrieved from the runtime."""

    min_task_size: int = dataclasses.field(
        default=1000, metadata={"argument": "min-task-size"}
    )
    """The minimum task size for sharding parallel operation."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class AsyncRuntimePolicyBasedRefCounting(Pass):
    """``async-runtime-policy-based-ref-counting``: Policy based reference counting for Async runtime operations

    This pass works at the async runtime abtraction level, after all
    `async.execute` and `async.await` operations are lowered to the async
    runtime API calls, and async coroutine operations.

    This pass doesn't rely on reference counted values liveness analysis, and
    instead uses simple policy to create reference counting operations. If the
    program violates any of the assumptions, then this pass might lead to
    memory leaks or runtime errors.

    The default reference counting policy assumptions:
      1. Async token can be awaited or added to the group only once.
      2. Async value or group can be awaited only once.

    Under these assumptions reference counting only needs to drop reference:
      1. After `async.runtime.await` operation for async tokens and groups
         (until error handling is not implemented for the sync await).
      2. After `async.runtime.is_error` operation for async tokens and groups
         (this is the last operation in the coroutine resume function).
      3. After `async.runtime.load` operation for async values.

    This pass introduces significanly less runtime overhead compared to the
    automatic reference counting.
    """

    ARGUMENT: ClassVar[str] = "async-runtime-policy-based-ref-counting"


@dataclasses.dataclass(frozen=True, kw_only=True)
class AsyncRuntimeRefCounting(Pass):
    """``async-runtime-ref-counting``: Automatic reference counting for Async runtime operations

    This pass works at the async runtime abtraction level, after all
    `async.execute` and `async.await` operations are lowered to the async
    runtime API calls, and async coroutine operations.

    It relies on the LLVM coroutines switched-resume lowering semantics for
    the correct placing of the reference counting operations.

    See: https://llvm.org/docs/Coroutines.html#switched-resume-lowering
    """

    ARGUMENT: ClassVar[str] = "async-runtime-ref-counting"


@dataclasses.dataclass(frozen=True, kw_only=True)
class AsyncRuntimeRefCountingOpt(Pass):
    """``async-runtime-ref-counting-opt``: Optimize automatic reference counting operations for theAsync runtime by removing redundant operations"""

    ARGUMENT: ClassVar[str] = "async-runtime-ref-counting-opt"


@dataclasses.dataclass(frozen=True, kw_only=True)
class AsyncToAsyncRuntime(Pass):
    """``async-to-async-runtime``: Lower all high level async operations (e.g. async.execute) tothe explicit async.runtime and async.coro operations"""

    ARGUMENT: ClassVar[str] = "async-to-async-runtime"
    ANCHOR: ClassVar[type[Operation] | None] = Module


@dataclasses.dataclass(frozen=True, kw_only=True)
class BubbleDownMemorySpaceCasts(Pass):
    """``bubble-down-memory-space-casts``: Bubbles down memory-space cast operations.

    This pass tries to iteratively bubble down all possible memory-space cast
    operations. It is important to note that the determination of which casts
    are bubbled down is based on the interfaces
    `MemorySpaceCastConsumerOpInterface`, and `MemorySpaceCastOpInterface`, and
    not the pass. The pass only looks for operations implementing the
    `MemorySpaceCastConsumerOpInterface` interface, and invoking the interface
    methods to perform the bubbling down.

    Example:

    ```mlir
    func.func @op_with_cast_sequence(%arg0: memref<4x4xf32, 1>, %arg1: index, %arg2: f32) -> memref<16xf32> {
      %memspacecast = memref.memory_space_cast %arg0 : memref<4x4xf32, 1> to memref<4x4xf32>
      %c0 = arith.constant 0 : index
      %c4 = arith.constant 4 : index
      %expanded = memref.expand_shape %memspacecast [[0], [1, 2]] output_shape [4, 2, 2] : memref<4x4xf32> into memref<4x2x2xf32>
      %collapsed = memref.collapse_shape %expanded [[0, 1, 2]] : memref<4x2x2xf32> into memref<16xf32>
      %loaded = memref.load %collapsed[%c0] : memref<16xf32>
      %added = arith.addf %loaded, %arg2 : f32
      memref.store %added, %collapsed[%c0] : memref<16xf32>
      %atomic_result = memref.atomic_rmw addf %arg2, %collapsed[%c4] : (f32, memref<16xf32>) -> f32
      return %collapsed : memref<16xf32>
    }
    // mlir-opt --bubble-down-memory-space-casts
    func.func @op_with_cast_sequence(%arg0: memref<4x4xf32, 1>, %arg1: index, %arg2: f32) -> memref<16xf32> {
      %c4 = arith.constant 4 : index
      %c0 = arith.constant 0 : index
      %expand_shape = memref.expand_shape %arg0 [[0], [1, 2]] output_shape [4, 2, 2] : memref<4x4xf32, 1> into memref<4x2x2xf32, 1>
      %collapse_shape = memref.collapse_shape %expand_shape [[0, 1, 2]] : memref<4x2x2xf32, 1> into memref<16xf32, 1>
      %memspacecast = memref.memory_space_cast %collapse_shape : memref<16xf32, 1> to memref<16xf32>
      %0 = memref.load %collapse_shape[%c0] : memref<16xf32, 1>
      %1 = arith.addf %0, %arg2 : f32
      memref.store %1, %collapse_shape[%c0] : memref<16xf32, 1>
      %2 = memref.atomic_rmw addf %arg2, %collapse_shape[%c4] : (f32, memref<16xf32, 1>) -> f32
      return %memspacecast : memref<16xf32>
    }
    ```
    """

    ARGUMENT: ClassVar[str] = "bubble-down-memory-space-casts"


@dataclasses.dataclass(frozen=True, kw_only=True)
class BufferDeallocationSimplification(Pass):
    """``buffer-deallocation-simplification``: Optimizes `bufferization.dealloc` operation for more efficient codegen

    This pass uses static alias analysis to reduce the number of alias checks
    required at runtime. Such checks are sometimes necessary to make sure that
    memrefs aren't deallocated before their last usage (use after free) or that
    some memref isn't deallocated twice (double free).
    """

    ARGUMENT: ClassVar[str] = "buffer-deallocation-simplification"


@dataclasses.dataclass(frozen=True, kw_only=True)
class BufferHoisting(Pass):
    """``buffer-hoisting``: Optimizes placement of allocation operations by moving them into common dominators and out of nested regions

    This pass implements an approach to aggressively move allocations upwards
    into common dominators and out of nested regions.
    """

    ARGUMENT: ClassVar[str] = "buffer-hoisting"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp


@dataclasses.dataclass(frozen=True, kw_only=True)
class BufferLoopHoisting(Pass):
    """``buffer-loop-hoisting``: Optimizes placement of allocation operations by moving them out of loop nests

    This pass implements an approach to aggressively move allocations upwards
    out of loop nests. It does not move allocations into common dominators.
    """

    ARGUMENT: ClassVar[str] = "buffer-loop-hoisting"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp


@dataclasses.dataclass(frozen=True, kw_only=True)
class BufferResultsToOutParams(Pass):
    """``buffer-results-to-out-params``: Converts memref-typed function results to out-params

    Some calling conventions prefer to pass output memrefs as "out params". The
    conversion to this calling convention must be done as an atomic
    transformation of the entire program (hence this is a module pass).

    For example, if a call is rewritten, the callee needs to be rewritten
    otherwise the IR will end up invalid. Thus, this transformation
    require an atomic change to the entire program (e.g. the whole module).

    This pass is expected to run immediately after bufferization is finished.
    At that point, tensor-typed results will have been converted to memref-typed
    results, and can be consistently converted to out params.

    All memref-typed results are appended to the function argument list.

    The main issue with this pass (and the out-param calling convention) is that
    buffers for results need to be allocated in the caller. This currently only
    works for static shaped memrefs.

    If the hoist-static-allocs option is on, the pass tries to eliminate the
    allocation for the returned memref and avoid the memory-copy if possible.
    This optimization applies on the returned memref which has static shape and
    is allocated by memref.alloc in the function. It will use the memref given
    in function argument to replace the allocated memref.
    """

    ARGUMENT: ClassVar[str] = "buffer-results-to-out-params"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    add_result_attr: bool = dataclasses.field(
        default=False, metadata={"argument": "add-result-attr"}
    )
    """Add the attribute 'bufferize.result' to all output parameters."""

    hoist_static_allocs: bool = dataclasses.field(
        default=False, metadata={"argument": "hoist-static-allocs"}
    )
    """Hoist static allocations to call sites."""

    hoist_dynamic_allocs: bool = dataclasses.field(
        default=False, metadata={"argument": "hoist-dynamic-allocs"}
    )
    """Hoist dynamic allocations to call sites."""

    modify_public_functions: bool = dataclasses.field(
        default=False, metadata={"argument": "modify-public-functions"}
    )
    """Modify function signatures of public functions."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class CSE(Pass):
    """``cse``: Eliminate common sub-expressions

    This pass implements a generalized algorithm for common sub-expression
    elimination. This pass relies on information provided by the
    `Memory SideEffect` interface to identify when it is safe to eliminate
    operations. See [Common subexpression elimination](https://en.wikipedia.org/wiki/Common_subexpression_elimination)
    for more general details on this optimization.
    """

    ARGUMENT: ClassVar[str] = "cse"


@dataclasses.dataclass(frozen=True, kw_only=True)
class Canonicalizer(Pass):
    """``canonicalize``: Canonicalize operations

    This pass performs various types of canonicalizations over a set of
    operations by iteratively applying the canonicalization patterns of all
    loaded dialects until either a fixpoint is reached or the maximum number of
    iterations/rewrites is exhausted. Canonicalization is best-effort and does
    not guarantee that the entire IR is in a canonical form after running this
    pass. See [Operation Canonicalization](Canonicalization.md) for more
    details.
    """

    ARGUMENT: ClassVar[str] = "canonicalize"

    top_down: bool = dataclasses.field(default=True, metadata={"argument": "top-down"})
    """Seed the worklist in general top-down order"""

    region_simplify: GreedySimplifyRegionLevel = dataclasses.field(
        default=GreedySimplifyRegionLevel.NORMAL,
        metadata={"argument": "region-simplify"},
    )
    """Perform control flow optimizations to the region tree"""

    max_iterations: int = dataclasses.field(
        default=10, metadata={"argument": "max-iterations"}
    )
    """Max. iterations between applying patterns / simplifying regions"""

    max_num_rewrites: int = dataclasses.field(
        default=-1, metadata={"argument": "max-num-rewrites"}
    )
    """Max. number of pattern rewrites within an iteration"""

    test_convergence: bool = dataclasses.field(
        default=False, metadata={"argument": "test-convergence"}
    )
    """Test only: Fail pass on non-convergence to detect cyclic pattern"""

    disable_patterns: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "disable-patterns"}
    )
    """Labels of patterns that should be filtered out during application"""

    enable_patterns: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "enable-patterns"}
    )
    """Labels of patterns that should be used during application, all other patterns are filtered out"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class CompositeFixedPoint(Pass):
    """``composite-fixed-point-pass``: Composite fixed point pass

    Composite pass runs provided set of passes until fixed point or maximum
    number of iterations reached.
    """

    ARGUMENT: ClassVar[str] = "composite-fixed-point-pass"

    name: str = dataclasses.field(
        default="CompositeFixedPointPass", metadata={"argument": "name"}
    )
    """Composite pass display name"""

    pipeline: str = dataclasses.field(default="", metadata={"argument": "pipeline"})
    """Composite pass inner pipeline"""

    max_iterations: int = dataclasses.field(
        default=10, metadata={"argument": "max-iterations"}
    )
    """Maximum number of iterations if inner pipeline"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ControlFlowSink(Pass):
    """``control-flow-sink``: Sink operations into conditional blocks

    This pass implements control-flow sink on operations that implement
    `RegionBranchOpInterface` by moving dominating operations whose only uses
    are in a conditionally-executed regions into those regions so that
    executions paths where their results are not needed do not perform
    unnecessary computations.

    This is similar (but opposite) to loop-invariant code motion, which hoists
    operations out of regions executed more than once. The implementation of
    control-flow sink uses a simple and conversative cost model: operations are
    never duplicated and are only moved into singly-executed regions.

    It is recommended to run canonicalization first to remove unreachable
    blocks: ops in unreachable blocks may prevent other operations from being
    sunk as they may contain uses of their results
    """

    ARGUMENT: ClassVar[str] = "control-flow-sink"


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertArithToEmitC(Pass):
    """``convert-arith-to-emitc``: Convert Arith dialect to EmitC dialect"""

    ARGUMENT: ClassVar[str] = "convert-arith-to-emitc"


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertAsyncToLLVM(Pass):
    """``convert-async-to-llvm``: Convert the operations from the async dialect into the LLVM dialect

    Convert `async.execute` operations to LLVM coroutines and use async runtime
    API to execute them.
    """

    ARGUMENT: ClassVar[str] = "convert-async-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertBufferizationToMemRef(Pass):
    """``convert-bufferization-to-memref``: Convert operations from the Bufferization dialect to the MemRef dialect

    This pass converts bufferization operations into memref operations.

    In the current state, this pass only transforms a `bufferization.clone`
    operation into `memref.alloc` and `memref.copy` operations and
    `bufferization.dealloc` operations (the same way as the
    `-bufferization-lower-deallocations` pass). The conversion of `clone`
    operations is needed, since some clone operations could remain after
    applying several transformation processes. Currently, only `canonicalize`
    transforms clone operations or even eliminates them. This can lead to errors
    if any clone op survived after all conversion passes (starting from the
    bufferization dialect) are performed.

    See:
    https://llvm.discourse.group/t/bufferization-error-related-to-memref-clone/4665

    To avoid these errors, this pass can be performed as a last clean-up pass to
    transform remaining operations and to proceed in other dialects (memref
    e.g.).

    Note that this pass only transforms the operation without any further
    analyses. This pass does not consider any memory analysis or optimization
    and hence does not resolve any memory leaks.
    """

    ARGUMENT: ClassVar[str] = "convert-bufferization-to-memref"


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertControlFlowToLLVM(Pass):
    """``convert-cf-to-llvm``: Convert ControlFlow operations to the LLVM dialect

    Convert ControlFlow operations into LLVM IR dialect operations.

    If other operations are present and their results are required by the LLVM
    IR dialect operations, the pass will fail.  Any LLVM IR operations or types
    already present in the IR will be kept as is.
    """

    ARGUMENT: ClassVar[str] = "convert-cf-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertFuncToEmitC(Pass):
    """``convert-func-to-emitc``: Convert Func dialect to EmitC dialect"""

    ARGUMENT: ClassVar[str] = "convert-func-to-emitc"
    ANCHOR: ClassVar[type[Operation] | None] = Module


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertFuncToLLVM(Pass):
    """``convert-func-to-llvm``: Convert from the Func dialect to the LLVM dialect

    Convert Func dialect operations into the LLVM IR dialect operations.

    #### Input invariant

    -   no `tensor` types;
    -   all `vector` are one-dimensional;
    -   all blocks are reachable by following the successors of the first basic
        block;

    If other operations are present and their results are required by the LLVM
    IR dialect operations, the pass will fail.  Any LLVM IR operations or types
    already present in the IR will be kept as is.

    An LLVM datalayout string can be attached as an attribute to the module on
    which the pass anchors. Such an attribute is attached by calling the
    set-module-datalayout pass. If present, an llvm::DataLayout object is
    created from this attribute and used in the conversion to LLVM.

    #### Output IR

    Functions converted to LLVM IR. Function arguments types are converted
    one-to-one. Function results are converted one-to-one and, in case more than
    1 value is returned, packed into an LLVM IR struct type. Function calls and
    returns are updated accordingly. Block argument types are updated to use
    LLVM IR types.
    """

    ARGUMENT: ClassVar[str] = "convert-func-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    use_bare_ptr_memref_call_conv: bool = dataclasses.field(
        default=False, metadata={"argument": "use-bare-ptr-memref-call-conv"}
    )
    """Replace FuncOp's MemRef arguments with bare pointers to the MemRef element types"""

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertMathToEmitC(Pass):
    """``convert-math-to-emitc``: Convert some Math operations to EmitC call_opaque operations

    This pass converts supported Math ops to `call_opaque` ops targeting libc/libm
    functions. Unlike convert-math-to-funcs pass, converting to `call_opaque` ops
    allows to overload the same function with different argument types.
    """

    ARGUMENT: ClassVar[str] = "convert-math-to-emitc"

    language_target: LanguageTarget = dataclasses.field(
        default=LanguageTarget.C99, metadata={"argument": "language-target"}
    )
    """Select the language standard target for callees (c99 or cpp11)."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertMathToEmitCLibm(Pass):
    """``convert-math-to-emitc-libm``: Turn math operations into calls to the C or C++ math library

    Rewrites each scalar `f32`/`f64` math operation with a `<math.h>`
    counterpart (`math.sqrt` to `sqrtf`/`sqrt`, `math.isnan` to `isnan`, ...)
    as an `emitc.call_opaque`, or with `lower-to-cpp`, a call to the
    `<cmath>` overload (`std::sqrt`). `math.rsqrt` becomes a division by the
    square root. The module includes the header when any call is made.
    Covers every math operation `convert-math-to-emitc` does and the rest
    of the C99 library.
    """

    ARGUMENT: ClassVar[str] = "convert-math-to-emitc-libm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    lower_to_cpp: bool = dataclasses.field(
        default=False, metadata={"argument": "lower-to-cpp"}
    )
    """Call the C++ library (std::sqrt in <cmath>) instead of C's"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertMathToLLVM(Pass):
    """``convert-math-to-llvm``: Convert Math dialect to LLVM dialect"""

    ARGUMENT: ClassVar[str] = "convert-math-to-llvm"

    approximate_log1p: bool = dataclasses.field(
        default=True, metadata={"argument": "approximate-log1p"}
    )
    """Enable approximation of Log1p."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertMemRefToEmitC(Pass):
    """``convert-memref-to-emitc``: Convert MemRef dialect to EmitC dialect"""

    ARGUMENT: ClassVar[str] = "convert-memref-to-emitc"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    lower_to_cpp: bool = dataclasses.field(
        default=False, metadata={"argument": "lower-to-cpp"}
    )
    """Target C++ (true) instead of C (false)"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertToEmitC(Pass):
    """``convert-to-emitc``: Convert to EmitC dialect via dialect interfaces

    This is a generic pass to convert to the EmitC dialect, it uses the
    `ConvertToEmitCPatternInterface` dialect interface to delegate to dialects
    the injection of conversion patterns.
    """

    ARGUMENT: ClassVar[str] = "convert-to-emitc"

    filter_dialects: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "filter-dialects"}
    )
    """Test conversion patterns of only the specified dialects"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertToLLVM(Pass):
    """``convert-to-llvm``: Convert to LLVM via dialect interfaces found in the input IR

    This is a generic pass to convert to LLVM, it uses the
    `ConvertToLLVMPatternInterface` dialect interface to delegate to dialects
    the injection of conversion patterns.

    If `dynamic` is set to `true`, the pass will look for
    `ConvertToLLVMAttrInterface` attributes and use them to further configure
    the conversion process. This option also uses the `DataLayoutAnalysis`
    analysis to configure the type converter. Enabling this option incurs in
    extra overhead.
    """

    ARGUMENT: ClassVar[str] = "convert-to-llvm"

    filter_dialects: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "filter-dialects"}
    )
    """Test conversion patterns of only the specified dialects"""

    dynamic: bool = dataclasses.field(default=False, metadata={"argument": "dynamic"})
    """Use op conversion attributes to configure the conversion"""

    allow_pattern_rollback: bool = dataclasses.field(
        default=True, metadata={"argument": "allow-pattern-rollback"}
    )
    """Experimental performance flag to disallow pattern rollback"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertVectorToLLVM(Pass):
    """``convert-vector-to-llvm``: Lower the operations from the vector dialect into the LLVM dialect

    Convert operations from the vector dialect into the LLVM IR dialect
    operations. The lowering pass provides several options to control
    the kinds of optimizations that are allowed. It also provides options
    that enable the use of one or more architectural-specific dialects
    (AMX, X86Vector, ArmNeon, ArmSVE, etc.) in combination with the
    architectural-neutral vector dialect lowering.
    """

    ARGUMENT: ClassVar[str] = "convert-vector-to-llvm"

    reassociate_fp_reductions: bool = dataclasses.field(
        default=False, metadata={"argument": "reassociate-fp-reductions"}
    )
    """Allows llvm to reassociate floating-point reductions for speed"""

    force_32bit_vector_indices: bool = dataclasses.field(
        default=True, metadata={"argument": "force-32bit-vector-indices"}
    )
    """Allows compiler to assume vector indices fit in 32-bit if that yields faster code"""

    use_vector_alignment: bool = dataclasses.field(
        default=False, metadata={"argument": "use-vector-alignment"}
    )
    """Use the preferred alignment of a vector type in load/store operations instead of the alignment of the element type of the memref. This flag is intended for use with hardware which requiresvector alignment, or in application contexts where it is known all vector access are naturally aligned. If operations have an alignment attribute set, the alignment attribute takes priority over this option"""

    enable_amx: bool = dataclasses.field(
        default=False, metadata={"argument": "enable-amx"}
    )
    """Enables the use of AMX dialect while lowering the vector dialect."""

    enable_arm_neon: bool = dataclasses.field(
        default=False, metadata={"argument": "enable-arm-neon"}
    )
    """Enables the use of ArmNeon dialect while lowering the vector dialect."""

    enable_arm_sve: bool = dataclasses.field(
        default=False, metadata={"argument": "enable-arm-sve"}
    )
    """Enables the use of ArmSVE dialect while lowering the vector dialect."""

    enable_arm_i8mm: bool = dataclasses.field(
        default=False, metadata={"argument": "enable-arm-i8mm"}
    )
    """Enables the use of Arm FEAT_I8MM instructions while lowering the vector dialect."""

    enable_arm_bf16: bool = dataclasses.field(
        default=False, metadata={"argument": "enable-arm-bf16"}
    )
    """Enables the use of Arm FEAT_BF16 instructions while lowering the vector dialect."""

    enable_x86vector: bool = dataclasses.field(
        default=False, metadata={"argument": "enable-x86vector"}
    )
    """Enables the use of X86Vector dialect while lowering the vector dialect."""

    vector_contract_lowering: VectorContractLowering = dataclasses.field(
        default=VectorContractLowering.DOT,
        metadata={"argument": "vector-contract-lowering"},
    )
    """control the lowering of `vector.contract` operations."""

    vector_transpose_lowering: VectorTransposeLowering = dataclasses.field(
        default=VectorTransposeLowering.ELTWISE,
        metadata={"argument": "vector-transpose-lowering"},
    )
    """control the lowering of `vector.transpose` operations."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ConvertVectorToSCF(Pass):
    """``convert-vector-to-scf``: Lower the operations from the vector dialect into the SCF dialect"""

    ARGUMENT: ClassVar[str] = "convert-vector-to-scf"

    full_unroll: bool = dataclasses.field(
        default=False, metadata={"argument": "full-unroll"}
    )
    """Perform full unrolling when converting vector transfers to SCF"""

    target_rank: int = dataclasses.field(
        default=1, metadata={"argument": "target-rank"}
    )
    """Target vector rank to which transfer ops should be lowered"""

    lower_tensors: bool = dataclasses.field(
        default=False, metadata={"argument": "lower-tensors"}
    )
    """Lower transfer ops that operate on tensors"""

    lower_scalable: bool = dataclasses.field(
        default=False, metadata={"argument": "lower-scalable"}
    )
    """Add scalable vector specific lowerings (that introduce loops)"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class DropEquivalentBufferResults(Pass):
    """``drop-equivalent-buffer-results``: Remove MemRef return values that are equivalent to a bbArg

    This pass removes MemRef return values from functions if they are equivalent
    to a function bbArg. In that case, the return value is redundant and the
    respective CallOp operand can be used at the call site.

    Note: If a bbArg buffer is not returned directly but casted to beforehand,
    the buffer is still considered equivalent.
    """

    ARGUMENT: ClassVar[str] = "drop-equivalent-buffer-results"
    ANCHOR: ClassVar[type[Operation] | None] = Module


@dataclasses.dataclass(frozen=True, kw_only=True)
class EmptyTensorElimination(Pass):
    """``eliminate-empty-tensors``: Try to eliminate all tensor.empty ops.

    Try to eliminate "tensor.empty" ops inside `op`. This transformation looks
    for subset ops that insert a tensor that originates from a "tensor.empty"
    (as per the reverse use-def chain). Such "tensor.empty" ops are replaced
    with the destination subset.

    E.g.:
    ```
    %0 = tensor.empty() : tensor<10xf32>
    %1 = linalg.fill ... outs(%0 : tensor<10xf32>)
    %2 = tensor.insert_slice %1 into %t ...
    ```

    In the above example, the subset op is "tensor.insert_slice". When tracing
    back the reverse use-def chain of a the source, we end up at a
    "tensor.empty" op. The "tensor.empty" op is replaced with a
    "tensor.extract_slice" op.
    """

    ARGUMENT: ClassVar[str] = "eliminate-empty-tensors"


@dataclasses.dataclass(frozen=True, kw_only=True)
class EmptyTensorToAllocTensor(Pass):
    """``empty-tensor-to-alloc-tensor``: Replace all empty ops by alloc_tensor ops.

    tensor.empty ops return a tensor of unspecified contents who's only purpose
    is to carry the tensor shape. This pass converts such ops to
    bufferization.alloc_tensor ops, which bufferize to buffer allocations.
    """

    ARGUMENT: ClassVar[str] = "empty-tensor-to-alloc-tensor"


@dataclasses.dataclass(frozen=True, kw_only=True)
class ExpandRealloc(Pass):
    """``expand-realloc``: Expand memref.realloc operations into its components

    The `memref.realloc` operation performs a conditional allocation and copy to
    increase the size of a buffer if necessary. This pass converts a `realloc`
    operation into this sequence of simpler operations such that other passes
    at a later stage in the compilation pipeline do not have to consider the
    `realloc` operation anymore (e.g., the buffer deallocation pass and the
    conversion pass to LLVM).

    Example of an expansion:
    ```mlir
    %realloc = memref.realloc %alloc (%size) : memref<?xf32> to memref<?xf32>
    ```
    is expanded to
    ```mlir
    %c0 = arith.constant 0 : index
    %dim = memref.dim %alloc, %c0 : memref<?xf32>
    %is_old_smaller = arith.cmpi ult, %dim, %arg1
    %realloc = scf.if %is_old_smaller -> (memref<?xf32>) {
      %new_alloc = memref.alloc(%size) : memref<?xf32>
      %subview = memref.subview %new_alloc[0] [%dim] [1]
      memref.copy %alloc, %subview
      memref.dealloc %alloc
      scf.yield %alloc_0 : memref<?xf32>
    } else {
      %reinterpret_cast = memref.reinterpret_cast %alloc to
        offset: [0], sizes: [%size], strides: [1]
      scf.yield %reinterpret_cast : memref<?xf32>
    }
    ```
    """

    ARGUMENT: ClassVar[str] = "expand-realloc"

    emit_deallocs: bool = dataclasses.field(
        default=True, metadata={"argument": "emit-deallocs"}
    )
    """Emit deallocation operations for the original MemRef"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class FinalizeMemRefToLLVMConversion(Pass):
    """``finalize-memref-to-llvm``: Finalize MemRef dialect to LLVM dialect conversion

    Finalize the conversion of the operations from the MemRef
    dialect to the LLVM dialect.
    This conversion will not convert some complex MemRef
    operations. Make sure to run `expand-strided-metadata`
    beforehand for these.
    """

    ARGUMENT: ClassVar[str] = "finalize-memref-to-llvm"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    use_aligned_alloc: bool = dataclasses.field(
        default=False, metadata={"argument": "use-aligned-alloc"}
    )
    """Use aligned_alloc in place of malloc for heap allocations"""

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""

    use_generic_functions: bool = dataclasses.field(
        default=False, metadata={"argument": "use-generic-functions"}
    )
    """Use generic allocation and deallocation functions instead of the classic 'malloc', 'aligned_alloc' and 'free' functions"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class FormExpressions(Pass):
    """``form-expressions``: Form C-style expressions from C-operator ops

    The pass wraps emitc ops modelling C operators in emitc.expression ops and
    then folds single-use expressions into their users where possible.
    """

    ARGUMENT: ClassVar[str] = "form-expressions"


@dataclasses.dataclass(frozen=True, kw_only=True)
class GenerateRuntimeVerification(Pass):
    """``generate-runtime-verification``: Generate additional runtime op verification checks

    This pass generates op-specific runtime checks using the
    `RuntimeVerifiableOpInterface`. It can be run for debugging purposes after
    passes that are suspected to introduce faulty IR.
    """

    ARGUMENT: ClassVar[str] = "generate-runtime-verification"

    verbose_level: int = dataclasses.field(
        default=1, metadata={"argument": "verbose-level"}
    )
    """Verbosity level for runtime verification messages: 0 = Minimum (only source location), 1 = Detailed (include full operation details, names, types, shapes, etc.)"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class Inliner(Pass):
    """``inline``: Inline function calls"""

    ARGUMENT: ClassVar[str] = "inline"

    default_pipeline: str = dataclasses.field(
        default="canonicalize", metadata={"argument": "default-pipeline"}
    )
    """The optimizer pipeline used for callables that do not have a dedicated optimizer pipeline in opPipelineList"""

    op_pipelines: Sequence[Nested] = dataclasses.field(
        default=(), metadata={"argument": "op-pipelines"}
    )
    """Callable operation specific optimizer pipelines (in the form of `dialect.op(pipeline)`)"""

    max_iterations: int = dataclasses.field(
        default=4, metadata={"argument": "max-iterations"}
    )
    """Maximum number of iterations when inlining within an SCC"""

    inlining_threshold: int = dataclasses.field(
        default=-1, metadata={"argument": "inlining-threshold"}
    )
    """If the ratio between the number of the operations in the callee and the number of the operations in the caller exceeds this value (in percentage), then the callee is not inlined even if it is legal to inline it"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class LiftControlFlowToSCF(Pass):
    """``lift-cf-to-scf``: Lift ControlFlow dialect to SCF dialect

    Lifts ControlFlow operations to SCF dialect operations.

    This pass is prefixed with "lift" instead of "convert" as it is not always
    guaranteed to replace all ControlFlow ops.
    If a region contains only a single kind of return-like operation, all
    ControlFlow operations will be replaced successfully.
    Otherwise a single ControlFlow switch branching to one block per return-like
    operation kind remains.

    This pass may need to create unreachable terminators in case of infinite
    loops, which is only supported for 'func.func' for now. If you potentially
    have infinite loops inside CFG regions not belonging to 'func.func',
    consider using `transformCFGToSCF` function directly with corresponding
    `CFGToSCFInterface::createUnreachableTerminator` implementation.
    """

    ARGUMENT: ClassVar[str] = "lift-cf-to-scf"


@dataclasses.dataclass(frozen=True, kw_only=True)
class LocationSnapshot(Pass):
    """``snapshot-op-locations``: Generate new locations from the current IR

    This pass allows for generating new locations from the IR during any stage
    of compilation, by snapshotting the IR to a file and using that file to
    generate new locations for the operations.

    Depending on the value of the `tag` option, different resulting locations
    may be generated:

    * If unset, the original location of the operation is replaced.

    Example:

    ```mlir
    // old:
    ... loc("original_source.cpp":1:1)

    // new:
    ... loc("snapshot_source.mlir":10:10)
    ```

    * If set, the new location is fused with the original location in the form
    of a [`Name Location`](Dialects/Builtin.md/#nameloc) with the specified tag.

    Example:

    ```mlir
    // old:
    ... loc("original_source.cpp":1:1)

    // new:
    ... loc(fused["original_source.cpp":1:1, "snapshot"("snapshot_source.mlir":10:10)])
    ```
    """

    ARGUMENT: ClassVar[str] = "snapshot-op-locations"

    filename: str = dataclasses.field(default="", metadata={"argument": "filename"})
    """The filename to print the generated IR"""

    tag: str = dataclasses.field(default="", metadata={"argument": "tag"})
    """A tag to use when fusing the new locations with the original. If unset, the locations are replaced."""

    print_debuginfo: bool = dataclasses.field(
        default=False, metadata={"argument": "print-debuginfo"}
    )
    """Print debug info in MLIR output"""

    print_op_generic: bool = dataclasses.field(
        default=False, metadata={"argument": "print-op-generic"}
    )
    """Print the generic op form"""

    print_local_scope: bool = dataclasses.field(
        default=False, metadata={"argument": "print-local-scope"}
    )
    """Print with local scope and inline information (eliding aliases for attributes, types, and locations"""

    pretty_debuginfo: bool = dataclasses.field(
        default=False, metadata={"argument": "pretty-debuginfo"}
    )
    """Print pretty debug info in MLIR output"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class LoopInvariantCodeMotion(Pass):
    """``loop-invariant-code-motion``: Hoist loop invariant instructions outside of the loop"""

    ARGUMENT: ClassVar[str] = "loop-invariant-code-motion"


@dataclasses.dataclass(frozen=True, kw_only=True)
class LoopInvariantSubsetHoisting(Pass):
    """``loop-invariant-subset-hoisting``: Hoist loop invariant subset ops outside of the loop"""

    ARGUMENT: ClassVar[str] = "loop-invariant-subset-hoisting"


@dataclasses.dataclass(frozen=True, kw_only=True)
class LowerDeallocations(Pass):
    """``bufferization-lower-deallocations``: Lowers `bufferization.dealloc` operations to `memref.dealloc`operations

    This pass lowers `bufferization.dealloc` operations to the `memref` dialect.
    It can be applied to a `builtin.module` or operations implementing the
    `FunctionOpInterface`. For the latter, only simple `dealloc` operations can
    be lowered because the library function necessary for the fully generic
    lowering cannot be inserted. In this case, an error will be emitted.
    Next to `memref.dealloc` operations, it may also emit operations from the
    `arith`, `scf`, and `func` dialects to build conditional deallocations and
    library functions to avoid code-size blow-up.
    """

    ARGUMENT: ClassVar[str] = "bufferization-lower-deallocations"


@dataclasses.dataclass(frozen=True, kw_only=True)
class LowerVectorMask(Pass):
    """``lower-vector-mask``: Lower 'vector.mask' operations"""

    ARGUMENT: ClassVar[str] = "lower-vector-mask"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp


@dataclasses.dataclass(frozen=True, kw_only=True)
class LowerVectorMultiReduction(Pass):
    """``lower-vector-multi-reduction``: Lower 'vector.multi_reduction' operations"""

    ARGUMENT: ClassVar[str] = "lower-vector-multi-reduction"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp

    lowering_strategy: VectorMultiReductionLowering = dataclasses.field(
        default=VectorMultiReductionLowering.INNER_PARALLEL,
        metadata={"argument": "lowering-strategy"},
    )
    """Select the strategy to control how multi_reduction is lowered."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class LowerVectorToFromElementsToShuffleTree(Pass):
    """``lower-vector-to-from-elements-to-shuffle-tree``: Lower `vector.to_elements` and `vector.from_elements` to a tree of `vector.shuffle` operations"""

    ARGUMENT: ClassVar[str] = "lower-vector-to-from-elements-to-shuffle-tree"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp


@dataclasses.dataclass(frozen=True, kw_only=True)
class Mem2Reg(Pass):
    """``mem2reg``: Promotes memory slots into values.

    This pass removes loads out of and stores into a memory slot, and turns
    them into direct uses of SSA values. This is done generically using the
    `PromotableAllocationOpInterface`, `PromotableOpInterface` and
    `PromotableMemOpInterface` interfaces.

    This pass will attempt to compute which definitions of the content of
    the memory slot reach operations that use the memory slot pointer. It
    will rewire or remove operations that use the slot pointer so they no
    longer use it. If any of this is not possible, the IR will be left
    without mutation.

    This pass only supports unstructured control-flow. Promotion of operations
    within subregions will not happen.
    """

    ARGUMENT: ClassVar[str] = "mem2reg"

    region_simplify: bool = dataclasses.field(
        default=True, metadata={"argument": "region-simplify"}
    )
    """Perform control flow optimizations to the region tree"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class OneShotBufferize(Pass):
    """``one-shot-bufferize``: One-Shot Bufferize

    This pass bufferizes all ops that implement `BufferizableOpInterface`. It
    first performs an inplacability analysis on SSA use-def chains of tensor
    values to determine which OpOperands may bufferize in-place, i.e., without
    inserting a buffer copy. It then rewrites the IR, inserting a buffer
    allocation and copy for each OpOperand that was decided to bufferize
    out-of-place.

    One-Shot Bufferize (and `BufferizableOpInterface`) was designed for ops that
    are in destination-passing style. When bufferizing such ops, it is possible
    to reuse the buffer of a tensor OpOperand for a tensor OpResult. In essence,
    a possible destination of an operation is already passed as an SSA value.

    `tensor.insert` is an example for an op in destination-passing style. E.g.,
    when bufferizing `%t0 = tensor.insert %f into %dest[%idx]`, `buffer(%t0)` is
    identical to `buffer(%dest)` in the absence of RaW conflicts. As a counter
    example, `tensor.generate` is not in destination-passing style and always
    results in a new buffer allocation.

    One-Shot Bufferize does not deallocate any buffers that it allocates. The
    `-buffer-deallocation-pipeline` pipeline should be run after One-Shot
    Bufferize to insert the deallocation operations necessary to eliminate
    memory leaks.

    One-Shot Bufferize will by default reject IR that contains non-bufferizable
    op, i.e., ops that do not implemement BufferizableOpInterface. Such IR can
    be allowed with `allow-unknown-ops=1`. In that case, to_buffer and to_tensor
    ops will be generated at the bufferization boundary. This is useful for
    compatibility with existing partial bufferization passes: These can
    bufferize the remaining IR after running One-Shot Bufferize.

    Note: Running One-Shot Bufferize after a partial bufferization pass is
    currently not supported. Running partial bufferization passes after running
    One-Shot Bufferize is supported and the recommended way to gradually
    migrate from partial bufferization to One-Shot Bufferize.

    With `dialect-filter`, bufferization can be restricted to a set of dialects.
    If no filter is specified, all ops that implement `BufferizableOpInterface`
    are bufferized. Ops from the `std` dialect are an exception: These ops are
    always ignored, even if no filter is specified. When specifying a dialect
    filter and `allow-unknown-ops` is not turned on, bufferization would fail
    when encountering an op that is not included in the filter (even if it is
    bufferizable).

    One-Shot Bufferize will by default assume memref types with fully dynamic
    layout maps when a precise layout cannot be inferred. E.g., this is the case
    when wrapping a non-bufferizable op in to_buffer/to_tensor ops. This
    behavior can be overridden with `unknown-type-conversion`. Valid values are
    `fully-dynamic-layout-map` and `identity-layout-map`.

    For testing/debugging purposes, `test-analysis-only=1 print-conflicts=1`
    prints analysis results and explains why an OpOperand was decided to
    bufferize out-of-place. This is useful for understanding why One-Shot
    Bufferize chose to insert a certain buffer copy.

    `bufferize-function-boundaries` is an experimental flag for bufferizing
    `FuncOp`, `ReturnOp` and `CallOp`. This feature is still under development
    and supports only simple cases at the moment. In particular:

    * Recursive or circular function call graphs are not supported.
    * External functions (without bodies) that return a tensor are not
      supported.
    * Function with multiple blocks or multiple ReturnOps are not supported.
    * Layout maps on function signatures can be controlled with a separate
      `function-boundary-type-conversion` option, which is similar to
      `unknown-type-conversion` but supports an additional `infer-layout-map`
      option. `fully-dynamic-layout-map` and `identity-layout-map` ensure that
      function signatures bufferize to easily predictable types, potentially at
      the cost of additional casts and copies, respectively. When layout maps
      are inferred, function return types may be more precise, but less
      predictable. Function argument types cannot be inferred and always have
      fully dynamic layout maps with `infer-layout-map`.

    One-Shot Bufferize implements the following contract around function calls:
    The buffer of function arguments is always writable (unless annotated with
    `bufferization.writable = false`). A buffer copy may be inserted at the call
    site where necessary. Alias sets and equivalence info is propagated through
    function calls. Whenever a function is bufferized, all other functions that
    are being called were already analyzed and bufferized, so exact alias and
    equivalence information is available. This is why recursive function calls
    are not yet supported.

    One-Shot Bufferize gathers additional information during the analysis phase
    when function boundary bufferization is activated. E.g., whether a function
    argument is read/written and which returned values are aliasing/equivalent.
    For debugging purposes, such information can be printed with
    `test-analysis-only`.

    The order in which ops are analyzed is important. The analysis is greedy and
    ops that are analyzed earlier are more likely to bufferize in-place. The
    heuristic can be set with `analysis-heuristic`. At the moment, the following
    heuristics are available:

    * `bottom-up` (default): Analyze ops from bottom to top.
    * `top-down`: Analyze ops from top to bottom.
    * `fuzzer`: Randomize the ordering of ops with `analysis-fuzzer-seed`.
    * `bottom-up-from-terminators`: Traverse the reverse use-def chains of
      tensor IR, starting from region branch terminators (bottom-up). Nested
      regions are traversed before enclosing regions. Analyze the traversed ops
      first, then analyze the remaining ops bottom-up. This heuristic is useful
      for bufferizing loop constructs. One-Shot Bufferize currently supports
      only such IR where yielded tensor values bufferize to equivalent region
      iter_args, and first analyzing all ops on the path from the "yielding" op
      to the beginning of the loop body makes it more likely for the region
      iter_args and yielded values to bufferize to equivalent buffers.
    """

    ARGUMENT: ClassVar[str] = "one-shot-bufferize"
    ANCHOR: ClassVar[type[Operation] | None] = Module

    allow_return_allocs_from_loops: bool = dataclasses.field(
        default=False, metadata={"argument": "allow-return-allocs-from-loops"}
    )
    """Allows returning/yielding new allocations from a loop."""

    allow_unknown_ops: bool = dataclasses.field(
        default=False, metadata={"argument": "allow-unknown-ops"}
    )
    """Allows unknown (not bufferizable) ops in the input IR."""

    analysis_fuzzer_seed: int = dataclasses.field(
        default=0, metadata={"argument": "analysis-fuzzer-seed"}
    )
    """Test only: Analyze ops in random order with a given seed (fuzzer)"""

    analysis_heuristic: str = dataclasses.field(
        default="bottom-up", metadata={"argument": "analysis-heuristic"}
    )
    """Heuristic that control the IR traversal during analysis"""

    bufferize_function_boundaries: bool | None = dataclasses.field(
        default=None, metadata={"argument": "bufferize-function-boundaries"}
    )
    """Bufferize function boundaries (experimental)."""

    check_parallel_regions: bool = dataclasses.field(
        default=True, metadata={"argument": "check-parallel-regions"}
    )
    """Account for parallel regions in RaW analysis."""

    copy_before_write: bool = dataclasses.field(
        default=False, metadata={"argument": "copy-before-write"}
    )
    """Skip the analysis. Make a buffer copy on every write."""

    dialect_filter: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "dialect-filter"}
    )
    """Restrict bufferization to ops from these dialects."""

    dump_alias_sets: bool = dataclasses.field(
        default=False, metadata={"argument": "dump-alias-sets"}
    )
    """Test only: Annotate tensor IR with alias sets"""

    no_analysis_func_filter: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "no-analysis-func-filter"}
    )
    """Skip analysis of functions with these symbol names.Set copyBeforeWrite to true when bufferizing them."""

    function_boundary_type_conversion: LayoutMapOption = dataclasses.field(
        default=LayoutMapOption.INFER_LAYOUT_MAP,
        metadata={"argument": "function-boundary-type-conversion"},
    )
    """Controls layout maps when bufferizing function signatures."""

    must_infer_memory_space: bool = dataclasses.field(
        default=False, metadata={"argument": "must-infer-memory-space"}
    )
    """The memory space of an memref types must always be inferred. If unset, a default memory space of 0 is used otherwise."""

    use_encoding_for_memory_space: bool = dataclasses.field(
        default=False, metadata={"argument": "use-encoding-for-memory-space"}
    )
    """Use the Tensor encoding attribute for the memory space. Exclusive to the 'must-infer-memory-space' option"""

    test_analysis_only: bool = dataclasses.field(
        default=False, metadata={"argument": "test-analysis-only"}
    )
    """Test only: Only run inplaceability analysis and annotate IR"""

    print_conflicts: bool = dataclasses.field(
        default=False, metadata={"argument": "print-conflicts"}
    )
    """Test only: Annotate IR with RaW conflicts. Requires test-analysis-only."""

    unknown_type_conversion: LayoutMapOption = dataclasses.field(
        default=LayoutMapOption.FULLY_DYNAMIC_LAYOUT_MAP,
        metadata={"argument": "unknown-type-conversion"},
    )
    """Controls layout maps for non-inferrable memref types."""

    buffer_alignment: int = dataclasses.field(
        default=64, metadata={"argument": "buffer-alignment"}
    )
    """Sets the alignment of newly allocated buffers."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class OptimizeAllocationLiveness(Pass):
    """``optimize-allocation-liveness``: This pass optimizes the liveness of temp allocations in the input function

    This pass will find all operations that have a memory allocation effect.
    It will search for the corresponding deallocation and move it right after
    the last user of the allocation.
    This will optimize the liveness of the allocations.

    The pass is expected to run after the deallocation pipeline.
    """

    ARGUMENT: ClassVar[str] = "optimize-allocation-liveness"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp


@dataclasses.dataclass(frozen=True, kw_only=True)
class OwnershipBasedBufferDeallocation(Pass):
    """``ownership-based-buffer-deallocation``: Adds all required dealloc operations for all allocations in the input program

    This pass implements an algorithm to automatically introduce all required
    deallocation operations for all buffers in the input program. This ensures
    that the resulting program does not have any memory leaks.

    The Buffer Deallocation pass operates on the level of operations
    implementing the FunctionOpInterface. Such operations can take MemRefs as
    arguments, but also return them. To ensure compatibility among all functions
    (including external ones), some rules have to be enforced. They are just
    assumed to hold for all external functions. Functions for which the
    definition is available ideally also already adhere to the ABI.
    Otherwise, all MemRef write operations in the input IR must dominate all
    MemRef read operations in the input IR. Then, the pass may modify the input
    IR by inserting `bufferization.clone` operations such that the output IR
    adheres to the function boundary ABI:
    * When a MemRef is passed as a function argument, ownership is never
      acquired. It is always the caller's responsibility to deallocate such
      MemRefs.
    * Returning a MemRef from a function always passes ownership to the caller,
      i.e., it is also the caller's responsibility to deallocate MemRefs
      returned from a called function.
    * A function must not return a MemRef with the same allocated base buffer as
      one of its arguments (in this case a copy has to be created). Note that in
      this context two subviews of the same buffer that don't overlap are also
      considered an alias.

    It is recommended to bufferize all operations first such that no tensor
    values remain in the IR once this pass is applied. That way all allocated
    MemRefs will be properly deallocated without any additional manual work.
    Otherwise, the pass that bufferizes the remaining tensors is responsible to
    add the corresponding deallocation operations. Note that this pass does not
    consider any values of tensor type and assumes that MemRef values defined by
    `bufferization.to_buffer` do not return ownership and do not have to be
    deallocated. `bufferization.to_tensor` operations are handled similarly to
    `bufferization.clone` operations with the exception that the result value is
    not handled because it's a tensor (not a MemRef).

    Input

    ```mlir
    #map0 = affine_map<(d0) -> (d0)>
    module {
      func.func @condBranch(%arg0: i1,
                            %arg1: memref<2xf32>,
                            %arg2: memref<2xf32>) {
        cf.cond_br %arg0, ^bb1, ^bb2
      ^bb1:
        cf.br ^bb3(%arg1 : memref<2xf32>)
      ^bb2:
        %0 = memref.alloc() : memref<2xf32>
        linalg.generic {
          indexing_maps = [#map0, #map0],
          iterator_types = ["parallel"]}
        outs(%arg1, %0 : memref<2xf32>, memref<2xf32>) {
        ^bb0(%gen1_arg0: f32, %gen1_arg1: f32):
          %tmp1 = exp %gen1_arg0 : f32
          linalg.yield %tmp1 : f32
        }
        cf.br ^bb3(%0 : memref<2xf32>)
      ^bb3(%1: memref<2xf32>):
        "memref.copy"(%1, %arg2) : (memref<2xf32>, memref<2xf32>) -> ()
        return
      }
    }
    ```

    Output

    ```mlir
    #map = affine_map<(d0) -> (d0)>
    module {
      func.func @condBranch(%arg0: i1,
                            %arg1: memref<2xf32>,
                            %arg2: memref<2xf32>) {
        %false = arith.constant false
        %true = arith.constant true
        cf.cond_br %arg0, ^bb1, ^bb2
      ^bb1:  // pred: ^bb0
        cf.br ^bb3(%arg1, %false : memref<2xf32>, i1)
      ^bb2:  // pred: ^bb0
        %alloc = memref.alloc() : memref<2xf32>
        linalg.generic {
          indexing_maps = [#map, #map],
          iterator_types = ["parallel"]}
        outs(%arg1, %alloc : memref<2xf32>, memref<2xf32>)
        ^bb0(%out: f32, %out_0: f32):
          %2 = math.exp %out : f32
          linalg.yield %2, %out_0 : f32, f32
        }
        cf.br ^bb3(%alloc, %true : memref<2xf32>, i1)
      ^bb3(%0: memref<2xf32>, %1: i1):  // 2 preds: ^bb1, ^bb2
        memref.copy %0, %arg2 : memref<2xf32> to memref<2xf32>
        %base_buffer, %offset, %sizes, %strides =
          memref.extract_strided_metadata %0 :
          memref<2xf32> -> memref<f32>, index, index, index
        bufferization.dealloc (%base_buffer : memref<f32>) if (%1)
        return
      }
    }
    ```

    The `private-function-dynamic-ownership` pass option allows the pass to add
    additional arguments to private functions to dynamically give ownership of
    MemRefs to callees. This can enable earlier deallocations and allows the
    pass to by-pass the function boundary ABI and thus potentially leading to
    fewer MemRef clones being inserted. For example, the private function
    ```mlir
    func.func private @passthrough(%memref: memref<2xi32>) -> memref<2xi32> {
      return %memref : memref<2xi32>
    }
    ```
    would be converted to
    ```mlir
    func.func private @passthrough(%memref: memref<2xi32>,
                                   %ownership: i1) -> (memref<2xi32>, i1) {
      return %memref, %ownership : memref<2xi32>, i1
    }
    ```
    and thus allows the returned MemRef to alias with the MemRef passed as
    argument (which would otherwise be forbidden according to the function
    boundary ABI).
    """

    ARGUMENT: ClassVar[str] = "ownership-based-buffer-deallocation"

    private_function_dynamic_ownership: bool = dataclasses.field(
        default=False, metadata={"argument": "private-function-dynamic-ownership"}
    )
    """Allows to add additional arguments to private functions to dynamically pass ownership of memrefs to callees. This can enable earlier deallocations."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class PrintIR(Pass):
    """``print-ir``: Print IR on the debug stream

    Print the entire IR on the debug stream. This is meant for debugging
    purposes to inspect the IR at a specific point in the pipeline.
    """

    ARGUMENT: ClassVar[str] = "print-ir"

    label: str = dataclasses.field(default="", metadata={"argument": "label"})
    """Label"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class PrintOpStats(Pass):
    """``print-op-stats``: Print statistics of operations"""

    ARGUMENT: ClassVar[str] = "print-op-stats"

    json: bool = dataclasses.field(default=False, metadata={"argument": "json"})
    """print the stats as JSON"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class PromoteBuffersToStack(Pass):
    """``promote-buffers-to-stack``: Promotes heap-based allocations to automatically managed stack-based allocations

    This pass implements a simple algorithm to convert heap-based memory
    allocations to stack-based ones. It uses a built-in heuristic to decide
    whether it makes sense to convert an allocation. Furthermore, dynamic
    shaped buffers that are limited by the rank of the tensor can be
    converted. They are only transformed if they are considered to be small.
    """

    ARGUMENT: ClassVar[str] = "promote-buffers-to-stack"
    ANCHOR: ClassVar[type[Operation] | None] = func.FuncOp

    max_alloc_size_in_bytes: int = dataclasses.field(
        default=1024, metadata={"argument": "max-alloc-size-in-bytes"}
    )
    """Maximal size in bytes to promote allocations to stack."""

    max_rank_of_allocated_memref: int = dataclasses.field(
        default=1, metadata={"argument": "max-rank-of-allocated-memref"}
    )
    """Maximal memref rank to promote dynamic buffers."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ReconcileUnrealizedCasts(Pass):
    """``reconcile-unrealized-casts``: Simplify and eliminate unrealized conversion casts

    Eliminate `unrealized_conversion_cast` operations, commonly introduced by
    partial dialect conversions, that transitively convert a value to another
    value of the same type, that is:

    ```
    %0 = "producer.op"() : () -> !type.A
    %1 = unrealized_conversion_cast %0 : !type.A to !type.B
    %2 = unrealized_conversion_cast %1 : !type.B to !type.C
    %3 = unrealized_conversion_cast %2 : !type.C to !type.A
    "consumer.op"(%3) : (!type.A) -> ()
    ```

    Such situations appear when the consumer operation is converted by one pass
    and the producer operation is converted by another pass, each of which
    produces an unrealized cast. This pass can be used to clean up the IR.
    """

    ARGUMENT: ClassVar[str] = "reconcile-unrealized-casts"


@dataclasses.dataclass(frozen=True, kw_only=True)
class RemoveDeadValues(Pass):
    """``remove-dead-values``: Remove dead values

    The goal of this pass is optimization (reducing runtime) by removing
    unnecessary instructions. Unlike other passes that rely on local information
    gathered from patterns to accomplish optimization, this pass uses a full
    analysis of the IR, specifically, liveness analysis, and is thus more
    powerful.

    Currently, this pass performs the following optimizations:
    (A) Removes function arguments that are not live,
    (B) Removes function return values that are not live across all callers of
    the function,
    (C) Removes unneccesary operands, results, region arguments, and region
    terminator operands of region branch ops, and,
    (D) Removes simple and region branch ops that have all non-live results and
    don't affect memory in any way,

    iff

    the IR doesn't have any non-function symbol ops, non-call symbol user ops
    and branch ops.

    Here, a "simple op" refers to an op that isn't a symbol op, symbol-user op,
    region branch op, branch op, region branch terminator op, or return-like.

    It is noteworthy that we do not refer to non-live values as "dead" in this
    file to avoid confusing it with dead code analysis's "dead", which refers to
    unreachable code (code that never executes on hardware) while "non-live"
    refers to code that executes on hardware but is unnecessary. Thus, while the
    removal of dead code helps little in reducing runtime, removing non-live
    values should theoretically have significant impact (depending on the amount
    removed).

    It is also important to note that unlike other passes (like `canonicalize`)
    that apply op-specific optimizations through patterns, this pass uses
    different interfaces to handle various types of ops and tries to cover all
    existing ops through these interfaces.

    It is because of its reliance on (a) liveness analysis and (b) interfaces
    that makes it so powerful that it can optimize ops that don't have a
    canonicalizer and even when an op does have a canonicalizer, it can perform
    more aggressive optimizations, as observed in the test files associated with
    this pass.

    Example of optimization (A):-

    ```
    int add_2_to_y(int x, int y) {
      return 2 + y
    }

    print(add_2_to_y(3, 4))
    print(add_2_to_y(5, 6))
    ```

    becomes

    ```
    int add_2_to_y(int y) {
      return 2 + y
    }

    print(add_2_to_y(4))
    print(add_2_to_y(6))
    ```

    Example of optimization (B):-

    ```
    int, int get_incremented_values(int y) {
      store y somewhere in memory
      return y + 1, y + 2
    }

    y1, y2 = get_incremented_values(4)
    y3, y4 = get_incremented_values(6)
    print(y2)
    ```

    becomes

    ```
    int get_incremented_values(int y) {
      store y somewhere in memory
      return y + 2
    }

    y2 = get_incremented_values(4)
    y4 = get_incremented_values(6)
    print(y2)
    ```

    Example of optimization (C):-

    Assume only `%result1` is live here. Then,

    ```
    %result1, %result2, %result3 = scf.while (%arg1 = %operand1, %arg2 = %operand2) {
      %terminator_operand2 = add %arg2, %arg2
      %terminator_operand3 = mul %arg2, %arg2
      %terminator_operand4 = add %arg1, %arg1
      scf.condition(%terminator_operand1) %terminator_operand2, %terminator_operand3, %terminator_operand4
    } do {
    ^bb0(%arg3, %arg4, %arg5):
      %terminator_operand6 = add %arg4, %arg4
      %terminator_operand5 = add %arg5, %arg5
      scf.yield %terminator_operand5, %terminator_operand6
    }
    ```

    becomes

    ```
    %result1, %result2 = scf.while (%arg2 = %operand2) {
      %terminator_operand2 = add %arg2, %arg2
      %terminator_operand3 = mul %arg2, %arg2
      scf.condition(%terminator_operand1) %terminator_operand2, %terminator_operand3
    } do {
    ^bb0(%arg3, %arg4):
      %terminator_operand6 = add %arg4, %arg4
      scf.yield %terminator_operand6
    }
    ```

    It is interesting to see that `%result2` won't be removed even though it is
    not live because `%terminator_operand3` forwards to it and cannot be
    removed. And, that is because it also forwards to `%arg4`, which is live.

    Example of optimization (D):-

    ```
    int square_and_double_of_y(int y) {
      square = y ^ 2
      double = y * 2
      return square, double
    }

    sq, do = square_and_double_of_y(5)
    print(do)
    ```

    becomes

    ```
    int square_and_double_of_y(int y) {
      double = y * 2
      return double
    }

    do = square_and_double_of_y(5)
    print(do)
    ```

    Note: If `canonicalize` is set to "false", this pass does not remove any
    block arguments / op results from ops that implement the
    RegionBranchOpInterface. Instead, it just sets dead operands to
    "ub.poison".
    """

    ARGUMENT: ClassVar[str] = "remove-dead-values"

    canonicalize: bool = dataclasses.field(
        default=True, metadata={"argument": "canonicalize"}
    )
    """Canonicalize region branch ops"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class SCCP(Pass):
    """``sccp``: Sparse Conditional Constant Propagation

    This pass implements a general algorithm for sparse conditional constant
    propagation. This algorithm detects values that are known to be constant and
    optimistically propagates this throughout the IR. Any values proven to be
    constant are replaced, and removed if possible.

    This implementation is based on the algorithm described by Wegman and Zadeck
    in [“Constant Propagation with Conditional Branches”](https://dl.acm.org/doi/10.1145/103135.103136) (1991).
    """

    ARGUMENT: ClassVar[str] = "sccp"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SCFToControlFlow(Pass):
    """``convert-scf-to-cf``: Convert SCF dialect to ControlFlow dialect, replacing structured control flow with a CFG"""

    ARGUMENT: ClassVar[str] = "convert-scf-to-cf"

    allow_pattern_rollback: bool = dataclasses.field(
        default=True, metadata={"argument": "allow-pattern-rollback"}
    )
    """Experimental performance flag to disallow pattern rollback"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class SCFToEmitC(Pass):
    """``convert-scf-to-emitc``: Convert SCF dialect to EmitC dialect, maintaining structured control flow"""

    ARGUMENT: ClassVar[str] = "convert-scf-to-emitc"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SROA(Pass):
    """``sroa``: Scalar Replacement of Aggregates

    Scalar Replacement of Aggregates. Replaces allocations of aggregates into
    independant allocations of its elements.

    Allocators must implement `DestructurableAllocationOpInterface` to provide
    the list of memory slots for which destructuring should be attempted.

    This pass will only be applied if all accessors of the aggregate implement
    the `DestructurableAccessorOpInterface`. If the accessors provide a view
    into the struct, users of the view must ensure it is used in a type-safe
    manner and within bounds by implementing `TypeSafeOpInterface`.
    """

    ARGUMENT: ClassVar[str] = "sroa"


@dataclasses.dataclass(frozen=True, kw_only=True)
class StripDebugInfo(Pass):
    """``strip-debuginfo``: Strip debug info from all operations

    This pass strips the IR of any location information, by replacing all
    operation locations with [`unknown`](Dialects/Builtin.md/#unknownloc).
    """

    ARGUMENT: ClassVar[str] = "strip-debuginfo"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SymbolDCE(Pass):
    """``symbol-dce``: Eliminate dead symbols

    This pass deletes all symbols that are found to be unreachable. This is done
    by computing the set of operations that are known to be live, propagating
    that liveness to other symbols, and then deleting all symbols that are not
    within this live set. Live symbols are those that have a
    [visibility](SymbolsAndSymbolTables.md/#symbol-visibility) that extends
    beyond the IR, e.g. `public`, or those that are referenced by live symbols
    or other non-Symbol operations.

    For example, consider the following input:

    ```mlir
    func.func private @dead_private_function()
    func.func private @live_private_function()

    // Note: The `public` isn't necessary here, as this is the default.
    func.func public @public_function() {
      "foo.return"() {uses = [@live_private_function]} : () -> ()
    }
    ```

    A known live function, `public_function`, contains a reference to an
    otherwise non-live function `live_private_function`. After running
    `symbol-dce`, only these two symbols should remain, as the final symbol
    `dead_private_function` is not visible outside of the current IR and there
    are no links to known-live operations. After running, we get the expected:

    ```mlir
    func.func private @live_private_function()

    func.func public @public_function() {
      "foo.return"() {uses = [@live_private_function]} : () -> ()
    }
    ```

    See [Symbols and SymbolTables](SymbolsAndSymbolTables.md) for more
    information on `Symbols`.
    """

    ARGUMENT: ClassVar[str] = "symbol-dce"


@dataclasses.dataclass(frozen=True, kw_only=True)
class SymbolPrivatize(Pass):
    """``symbol-privatize``: Mark symbols private

    This pass marks all top-level symbols of the operation run as `private`
    except if listed in `exclude` pass option.
    """

    ARGUMENT: ClassVar[str] = "symbol-privatize"

    exclude: Sequence[str] = dataclasses.field(
        default=(), metadata={"argument": "exclude"}
    )
    """Comma separated list of symbols that should not be marked private"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class TopologicalSort(Pass):
    """``topological-sort``: Sort regions without SSA dominance in topological order

    Recursively sorts all nested regions without SSA dominance in topological
    order. The main purpose is readability, as well as potentially processing of
    certain transformations and analyses. The function sorts the operations in
    all nested regions such that, as much as possible, all users appear after
    their producers.

    This sort is stable. If the block is already topologically sorted, the IR
    is not changed. Operations that form a cycle are moved to the end of the
    regions in a stable order.
    """

    ARGUMENT: ClassVar[str] = "topological-sort"


@dataclasses.dataclass(frozen=True, kw_only=True)
class UBToLLVMConversion(Pass):
    """``convert-ub-to-llvm``: Convert UB dialect to LLVM dialect

    This pass converts supported UB ops to LLVM dialect instructions.
    """

    ARGUMENT: ClassVar[str] = "convert-ub-to-llvm"

    index_bitwidth: int = dataclasses.field(
        default=0, metadata={"argument": "index-bitwidth"}
    )
    """Bitwidth of the index type, 0 to use size of machine word"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class UpliftWhileToFor(Pass):
    """``scf-uplift-while-to-for``: Turn counted scf.while loops into scf.for

    Rewrites an `scf.while` loop whose condition compares an induction
    variable against a loop-invariant bound (`slt`/`sgt`) and whose body adds
    a loop-invariant step into an `scf.for` loop, the form that later
    parallelization and vectorization expect. Other loops are left as they
    are. Wraps MLIR's `populateUpliftWhileToForPatterns`.
    """

    ARGUMENT: ClassVar[str] = "scf-uplift-while-to-for"


@dataclasses.dataclass(frozen=True, kw_only=True)
class ViewOpGraph(Pass):
    """``view-op-graph``: Print Graphviz visualization of an operation

    This pass prints a Graphviz graph of a module.

    - Operations are represented as nodes;
    - Uses (data flow) as edges;
    - Control flow as dashed edges;
    - Regions/blocks as subgraphs.

    By default, only data flow edges are printed.

    Note: See https://www.graphviz.org/doc/info/lang.html for more information
    about the Graphviz DOT language.
    """

    ARGUMENT: ClassVar[str] = "view-op-graph"

    max_label_len: int = dataclasses.field(
        default=20, metadata={"argument": "max-label-len"}
    )
    """Limit attribute/type length to number of chars"""

    print_attrs: bool = dataclasses.field(
        default=True, metadata={"argument": "print-attrs"}
    )
    """Print attributes of operations"""

    print_control_flow_edges: bool = dataclasses.field(
        default=False, metadata={"argument": "print-control-flow-edges"}
    )
    """Print control flow edges"""

    print_data_flow_edges: bool = dataclasses.field(
        default=True, metadata={"argument": "print-data-flow-edges"}
    )
    """Print data flow edges"""

    print_result_types: bool = dataclasses.field(
        default=True, metadata={"argument": "print-result-types"}
    )
    """Print result types of operations"""


@dataclasses.dataclass(frozen=True, kw_only=True)
class WrapFuncInClass(Pass):
    """``wrap-emitc-func-in-class``: Wrap functions in classes, using arguments as fields.

    This pass transforms `emitc.func` operations into `emitc.class` operations.
    Function arguments become fields of the class, and the function body is moved
    to a new `execute` method within the class.
    If the corresponding function argument has attributes (accessed via `argAttrs`),
    these attributes are attached to the field operation.
    Otherwise, the field is created without additional attributes.

    Example:

    ```mlir
    emitc.func @model(%input_data : !emitc.array<1xf32> {emitc.opaque = "input_tensor"}) attributes { } {
      %0 = "emitc.constant"() <{value = 0 : index}> : () -> !emitc.size_t
      %1 = subscript %input_data[%0] : (!emitc.array<1xf32>, !emitc.size_t) -> !emitc.lvalue<f32>
      return
    }
    // becomes
    emitc.class @modelClass {
      emitc.field @input_tensor : !emitc.array<1xf32> {emitc.opaque = "input_tensor"}
      emitc.func @execute() {
        %0 = "emitc.constant"() <{value = 0 : index}> : () -> !emitc.size_t
        %1 = get_field @input_tensor : !emitc.array<1xf32>
        %2 = subscript %1[%0] : (!emitc.array<1xf32>, !emitc.size_t) -> !emitc.lvalue<f32>
        return
      }
    }
    ```
    """

    ARGUMENT: ClassVar[str] = "wrap-emitc-func-in-class"


__all__ = [
    "CSE",
    "SCCP",
    "SROA",
    "ArithToLLVMConversion",
    "AsyncFuncToAsyncRuntime",
    "AsyncParallelFor",
    "AsyncRuntimePolicyBasedRefCounting",
    "AsyncRuntimeRefCounting",
    "AsyncRuntimeRefCountingOpt",
    "AsyncToAsyncRuntime",
    "BubbleDownMemorySpaceCasts",
    "BufferDeallocationSimplification",
    "BufferHoisting",
    "BufferLoopHoisting",
    "BufferResultsToOutParams",
    "Canonicalizer",
    "CompositeFixedPoint",
    "ControlFlowSink",
    "ConvertArithToEmitC",
    "ConvertAsyncToLLVM",
    "ConvertBufferizationToMemRef",
    "ConvertControlFlowToLLVM",
    "ConvertFuncToEmitC",
    "ConvertFuncToLLVM",
    "ConvertMathToEmitC",
    "ConvertMathToEmitCLibm",
    "ConvertMathToLLVM",
    "ConvertMemRefToEmitC",
    "ConvertToEmitC",
    "ConvertToLLVM",
    "ConvertVectorToLLVM",
    "ConvertVectorToSCF",
    "DropEquivalentBufferResults",
    "EmptyTensorElimination",
    "EmptyTensorToAllocTensor",
    "ExpandRealloc",
    "FinalizeMemRefToLLVMConversion",
    "FormExpressions",
    "GenerateRuntimeVerification",
    "GreedySimplifyRegionLevel",
    "Inliner",
    "LanguageTarget",
    "LayoutMapOption",
    "LiftControlFlowToSCF",
    "LocationSnapshot",
    "LoopInvariantCodeMotion",
    "LoopInvariantSubsetHoisting",
    "LowerDeallocations",
    "LowerVectorMask",
    "LowerVectorMultiReduction",
    "LowerVectorToFromElementsToShuffleTree",
    "Mem2Reg",
    "Nested",
    "OneShotBufferize",
    "OptimizeAllocationLiveness",
    "OwnershipBasedBufferDeallocation",
    "Pass",
    "PassManager",
    "PipelineElement",
    "PrintIR",
    "PrintOpStats",
    "PromoteBuffersToStack",
    "PythonPass",
    "ReconcileUnrealizedCasts",
    "RemoveDeadValues",
    "SCFToControlFlow",
    "SCFToEmitC",
    "StripDebugInfo",
    "SymbolDCE",
    "SymbolPrivatize",
    "TopologicalSort",
    "UBToLLVMConversion",
    "UpliftWhileToFor",
    "VectorContractLowering",
    "VectorMultiReductionLowering",
    "VectorTransposeLowering",
    "ViewOpGraph",
    "WrapFuncInClass",
]
